// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface AzureBlobCredsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.AzureBlobCreds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string account_name = 1;</code>
   * @return The accountName.
   */
  java.lang.String getAccountName();
  /**
   * <code>string account_name = 1;</code>
   * @return The bytes for accountName.
   */
  com.google.protobuf.ByteString
      getAccountNameBytes();

  /**
   * <code>string account_key = 2;</code>
   * @return The accountKey.
   */
  java.lang.String getAccountKey();
  /**
   * <code>string account_key = 2;</code>
   * @return The bytes for accountKey.
   */
  com.google.protobuf.ByteString
      getAccountKeyBytes();
}
