// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface ConceptQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.ConceptQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the concept to search.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the concept to search.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The language of the concept name in a search. Defaults to English.
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * The language of the concept name in a search. Defaults to English.
   * </pre>
   *
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * Deprecated: Use workflow.id instead.
   * </pre>
   *
   * <code>string workflow_id = 3 [deprecated = true];</code>
   * @deprecated clarifai.api.ConceptQuery.workflow_id is deprecated.
   *     See proto/clarifai/api/resources.proto;l=561
   * @return The workflowId.
   */
  @java.lang.Deprecated java.lang.String getWorkflowId();
  /**
   * <pre>
   * Deprecated: Use workflow.id instead.
   * </pre>
   *
   * <code>string workflow_id = 3 [deprecated = true];</code>
   * @deprecated clarifai.api.ConceptQuery.workflow_id is deprecated.
   *     See proto/clarifai/api/resources.proto;l=561
   * @return The bytes for workflowId.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getWorkflowIdBytes();

  /**
   * <pre>
   * The concepts must belong to models with specified use cases.
   * Multiple values are joined using an OR condition.
   * </pre>
   *
   * <code>repeated .clarifai.api.WorkflowModelUseCase use_cases = 4;</code>
   * @return A list containing the useCases.
   */
  java.util.List<com.clarifai.grpc.api.WorkflowModelUseCase> getUseCasesList();
  /**
   * <pre>
   * The concepts must belong to models with specified use cases.
   * Multiple values are joined using an OR condition.
   * </pre>
   *
   * <code>repeated .clarifai.api.WorkflowModelUseCase use_cases = 4;</code>
   * @return The count of useCases.
   */
  int getUseCasesCount();
  /**
   * <pre>
   * The concepts must belong to models with specified use cases.
   * Multiple values are joined using an OR condition.
   * </pre>
   *
   * <code>repeated .clarifai.api.WorkflowModelUseCase use_cases = 4;</code>
   * @param index The index of the element to return.
   * @return The useCases at the given index.
   */
  com.clarifai.grpc.api.WorkflowModelUseCase getUseCases(int index);
  /**
   * <pre>
   * The concepts must belong to models with specified use cases.
   * Multiple values are joined using an OR condition.
   * </pre>
   *
   * <code>repeated .clarifai.api.WorkflowModelUseCase use_cases = 4;</code>
   * @return A list containing the enum numeric values on the wire for useCases.
   */
  java.util.List<java.lang.Integer>
  getUseCasesValueList();
  /**
   * <pre>
   * The concepts must belong to models with specified use cases.
   * Multiple values are joined using an OR condition.
   * </pre>
   *
   * <code>repeated .clarifai.api.WorkflowModelUseCase use_cases = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of useCases at the given index.
   */
  int getUseCasesValue(int index);

  /**
   * <code>.clarifai.api.Model model = 5;</code>
   * @return Whether the model field is set.
   */
  boolean hasModel();
  /**
   * <code>.clarifai.api.Model model = 5;</code>
   * @return The model.
   */
  com.clarifai.grpc.api.Model getModel();
  /**
   * <code>.clarifai.api.Model model = 5;</code>
   */
  com.clarifai.grpc.api.ModelOrBuilder getModelOrBuilder();

  /**
   * <code>.clarifai.api.Workflow workflow = 6;</code>
   * @return Whether the workflow field is set.
   */
  boolean hasWorkflow();
  /**
   * <code>.clarifai.api.Workflow workflow = 6;</code>
   * @return The workflow.
   */
  com.clarifai.grpc.api.Workflow getWorkflow();
  /**
   * <code>.clarifai.api.Workflow workflow = 6;</code>
   */
  com.clarifai.grpc.api.WorkflowOrBuilder getWorkflowOrBuilder();

  /**
   * <pre>
   * By default, we return app concepts combined with source (model or workflow) concepts.
   * If source is not set, then we only return app concepts.
   * If ignore_app_concepts is true, then we only return source concepts.
   * When use_cases are set, then ignore_app_concepts is always true, because
   * concept use cases can only be determined in relation to a model or a workflow.
   * </pre>
   *
   * <code>bool ignore_app_concepts = 7;</code>
   * @return The ignoreAppConcepts.
   */
  boolean getIgnoreAppConcepts();

  public com.clarifai.grpc.api.ConceptQuery.SourceCase getSourceCase();
}
