// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface DatasetInputsSearchAddJobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.DatasetInputsSearchAddJob)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of this job
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The id of this job
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * When the job was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * When the job was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * When the job was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * When the job was last modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 3;</code>
   * @return Whether the modifiedAt field is set.
   */
  boolean hasModifiedAt();
  /**
   * <pre>
   * When the job was last modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 3;</code>
   * @return The modifiedAt.
   */
  com.google.protobuf.Timestamp getModifiedAt();
  /**
   * <pre>
   * When the job was last modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder();

  /**
   * <pre>
   * Status of the job and rough estimated progress
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 4;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Status of the job and rough estimated progress
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 4;</code>
   * @return The status.
   */
  com.clarifai.grpc.api.status.Status getStatus();
  /**
   * <pre>
   * Status of the job and rough estimated progress
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 4;</code>
   */
  com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * Dataset which will receive inputs
   * </pre>
   *
   * <code>string dataset_id = 5;</code>
   * @return The datasetId.
   */
  java.lang.String getDatasetId();
  /**
   * <pre>
   * Dataset which will receive inputs
   * </pre>
   *
   * <code>string dataset_id = 5;</code>
   * @return The bytes for datasetId.
   */
  com.google.protobuf.ByteString
      getDatasetIdBytes();

  /**
   * <pre>
   * The search that the job uses
   * </pre>
   *
   * <code>.clarifai.api.Search search = 6;</code>
   * @return Whether the search field is set.
   */
  boolean hasSearch();
  /**
   * <pre>
   * The search that the job uses
   * </pre>
   *
   * <code>.clarifai.api.Search search = 6;</code>
   * @return The search.
   */
  com.clarifai.grpc.api.Search getSearch();
  /**
   * <pre>
   * The search that the job uses
   * </pre>
   *
   * <code>.clarifai.api.Search search = 6;</code>
   */
  com.clarifai.grpc.api.SearchOrBuilder getSearchOrBuilder();
}
