// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface DeploymentMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.DeploymentMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Deprecated: use aggregate instead.
   * </pre>
   *
   * <code>uint32 desired_replicas = 1 [deprecated = true];</code>
   * @deprecated clarifai.api.DeploymentMetrics.desired_replicas is deprecated.
   *     See proto/clarifai/api/resources.proto;l=4755
   * @return The desiredReplicas.
   */
  @java.lang.Deprecated int getDesiredReplicas();

  /**
   * <pre>
   * Deprecated: use aggregate instead.
   * </pre>
   *
   * <code>uint32 live_replicas = 2 [deprecated = true];</code>
   * @deprecated clarifai.api.DeploymentMetrics.live_replicas is deprecated.
   *     See proto/clarifai/api/resources.proto;l=4757
   * @return The liveReplicas.
   */
  @java.lang.Deprecated int getLiveReplicas();

  /**
   * <pre>
   * Deprecated: use aggregate instead.
   * </pre>
   *
   * <code>bool rollout_in_progress = 3 [deprecated = true];</code>
   * @deprecated clarifai.api.DeploymentMetrics.rollout_in_progress is deprecated.
   *     See proto/clarifai/api/resources.proto;l=4759
   * @return The rolloutInProgress.
   */
  @java.lang.Deprecated boolean getRolloutInProgress();

  /**
   * <pre>
   * Per-nodepool breakdown of metrics.
   * </pre>
   *
   * <code>repeated .clarifai.api.NodepoolDeploymentMetrics nodepool_metrics = 4;</code>
   */
  java.util.List<com.clarifai.grpc.api.NodepoolDeploymentMetrics> 
      getNodepoolMetricsList();
  /**
   * <pre>
   * Per-nodepool breakdown of metrics.
   * </pre>
   *
   * <code>repeated .clarifai.api.NodepoolDeploymentMetrics nodepool_metrics = 4;</code>
   */
  com.clarifai.grpc.api.NodepoolDeploymentMetrics getNodepoolMetrics(int index);
  /**
   * <pre>
   * Per-nodepool breakdown of metrics.
   * </pre>
   *
   * <code>repeated .clarifai.api.NodepoolDeploymentMetrics nodepool_metrics = 4;</code>
   */
  int getNodepoolMetricsCount();
  /**
   * <pre>
   * Per-nodepool breakdown of metrics.
   * </pre>
   *
   * <code>repeated .clarifai.api.NodepoolDeploymentMetrics nodepool_metrics = 4;</code>
   */
  java.util.List<? extends com.clarifai.grpc.api.NodepoolDeploymentMetricsOrBuilder> 
      getNodepoolMetricsOrBuilderList();
  /**
   * <pre>
   * Per-nodepool breakdown of metrics.
   * </pre>
   *
   * <code>repeated .clarifai.api.NodepoolDeploymentMetrics nodepool_metrics = 4;</code>
   */
  com.clarifai.grpc.api.NodepoolDeploymentMetricsOrBuilder getNodepoolMetricsOrBuilder(
      int index);

  /**
   * <pre>
   * Aggregate metrics across all nodepools.
   * </pre>
   *
   * <code>.clarifai.api.DeploymentMetricsSummary aggregate = 5;</code>
   * @return Whether the aggregate field is set.
   */
  boolean hasAggregate();
  /**
   * <pre>
   * Aggregate metrics across all nodepools.
   * </pre>
   *
   * <code>.clarifai.api.DeploymentMetricsSummary aggregate = 5;</code>
   * @return The aggregate.
   */
  com.clarifai.grpc.api.DeploymentMetricsSummary getAggregate();
  /**
   * <pre>
   * Aggregate metrics across all nodepools.
   * </pre>
   *
   * <code>.clarifai.api.DeploymentMetricsSummary aggregate = 5;</code>
   */
  com.clarifai.grpc.api.DeploymentMetricsSummaryOrBuilder getAggregateOrBuilder();
}
