// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface EvaluationMetricValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.EvaluationMetricValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The metric values
   * </pre>
   *
   * <code>string evaluation_metric_id = 1;</code>
   * @return The evaluationMetricId.
   */
  java.lang.String getEvaluationMetricId();
  /**
   * <pre>
   * The metric values
   * </pre>
   *
   * <code>string evaluation_metric_id = 1;</code>
   * @return The bytes for evaluationMetricId.
   */
  com.google.protobuf.ByteString
      getEvaluationMetricIdBytes();

  /**
   * <pre>
   * Aggregated metric value
   * </pre>
   *
   * <code>.clarifai.api.MetricValue metric_value = 2;</code>
   * @return Whether the metricValue field is set.
   */
  boolean hasMetricValue();
  /**
   * <pre>
   * Aggregated metric value
   * </pre>
   *
   * <code>.clarifai.api.MetricValue metric_value = 2;</code>
   * @return The metricValue.
   */
  com.clarifai.grpc.api.MetricValue getMetricValue();
  /**
   * <pre>
   * Aggregated metric value
   * </pre>
   *
   * <code>.clarifai.api.MetricValue metric_value = 2;</code>
   */
  com.clarifai.grpc.api.MetricValueOrBuilder getMetricValueOrBuilder();

  /**
   * <pre>
   * explanation for the value
   * </pre>
   *
   * <code>string explanation = 3;</code>
   * @return The explanation.
   */
  java.lang.String getExplanation();
  /**
   * <pre>
   * explanation for the value
   * </pre>
   *
   * <code>string explanation = 3;</code>
   * @return The bytes for explanation.
   */
  com.google.protobuf.ByteString
      getExplanationBytes();

  /**
   * <pre>
   * Metric values for each concept
   * </pre>
   *
   * <code>map&lt;string, .clarifai.api.MetricValue&gt; per_concept_values = 4;</code>
   */
  int getPerConceptValuesCount();
  /**
   * <pre>
   * Metric values for each concept
   * </pre>
   *
   * <code>map&lt;string, .clarifai.api.MetricValue&gt; per_concept_values = 4;</code>
   */
  boolean containsPerConceptValues(
      java.lang.String key);
  /**
   * Use {@link #getPerConceptValuesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.clarifai.grpc.api.MetricValue>
  getPerConceptValues();
  /**
   * <pre>
   * Metric values for each concept
   * </pre>
   *
   * <code>map&lt;string, .clarifai.api.MetricValue&gt; per_concept_values = 4;</code>
   */
  java.util.Map<java.lang.String, com.clarifai.grpc.api.MetricValue>
  getPerConceptValuesMap();
  /**
   * <pre>
   * Metric values for each concept
   * </pre>
   *
   * <code>map&lt;string, .clarifai.api.MetricValue&gt; per_concept_values = 4;</code>
   */

  /* nullable */
com.clarifai.grpc.api.MetricValue getPerConceptValuesOrDefault(
      java.lang.String key,
      /* nullable */
com.clarifai.grpc.api.MetricValue defaultValue);
  /**
   * <pre>
   * Metric values for each concept
   * </pre>
   *
   * <code>map&lt;string, .clarifai.api.MetricValue&gt; per_concept_values = 4;</code>
   */

  com.clarifai.grpc.api.MetricValue getPerConceptValuesOrThrow(
      java.lang.String key);
}
