// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

public interface ListKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.ListKeysRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return Whether the userAppId field is set.
   */
  boolean hasUserAppId();
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return The userAppId.
   */
  com.clarifai.grpc.api.UserAppIDSet getUserAppId();
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   */
  com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder();

  /**
   * <pre>
   * (optional URL parameter) The page number. Pagination is used to split the results into chunks.
   * Defaults to 1.
   * </pre>
   *
   * <code>uint32 page = 2;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * (optional URL parameter) The number of results that will be contained in each page. Defaults
   * to 128.
   * </pre>
   *
   * <code>uint32 per_page = 3;</code>
   * @return The perPage.
   */
  int getPerPage();

  /**
   * <code>bool not_expired = 4;</code>
   * @return The notExpired.
   */
  boolean getNotExpired();

  /**
   * <code>repeated string scopes = 5;</code>
   * @return A list containing the scopes.
   */
  java.util.List<java.lang.String>
      getScopesList();
  /**
   * <code>repeated string scopes = 5;</code>
   * @return The count of scopes.
   */
  int getScopesCount();
  /**
   * <code>repeated string scopes = 5;</code>
   * @param index The index of the element to return.
   * @return The scopes at the given index.
   */
  java.lang.String getScopes(int index);
  /**
   * <code>repeated string scopes = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the scopes at the given index.
   */
  com.google.protobuf.ByteString
      getScopesBytes(int index);

  /**
   * <code>repeated string endpoints = 6;</code>
   * @return A list containing the endpoints.
   */
  java.util.List<java.lang.String>
      getEndpointsList();
  /**
   * <code>repeated string endpoints = 6;</code>
   * @return The count of endpoints.
   */
  int getEndpointsCount();
  /**
   * <code>repeated string endpoints = 6;</code>
   * @param index The index of the element to return.
   * @return The endpoints at the given index.
   */
  java.lang.String getEndpoints(int index);
  /**
   * <code>repeated string endpoints = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the endpoints at the given index.
   */
  com.google.protobuf.ByteString
      getEndpointsBytes(int index);
}
