// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface ModelTypeRangeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.ModelTypeRangeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The start of the range as a float.
   * </pre>
   *
   * <code>float min = 1;</code>
   * @return The min.
   */
  float getMin();

  /**
   * <pre>
   * The end of the range as a float.
   * </pre>
   *
   * <code>float max = 2;</code>
   * @return The max.
   */
  float getMax();

  /**
   * <pre>
   * An optional step size for the range. If provided then only values at that step size will be
   * rounded to. For example if step is 0.02 then 0.0245 will round to 0.02.
   * </pre>
   *
   * <code>float step = 3;</code>
   * @return The step.
   */
  float getStep();
}
