// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

public interface PatchAppsDetailsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.PatchAppsDetailsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return Whether the userAppId field is set.
   */
  boolean hasUserAppId();
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return The userAppId.
   */
  com.clarifai.grpc.api.UserAppIDSet getUserAppId();
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   */
  com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder();

  /**
   * <code>repeated .clarifai.api.App apps = 2;</code>
   */
  java.util.List<com.clarifai.grpc.api.App> 
      getAppsList();
  /**
   * <code>repeated .clarifai.api.App apps = 2;</code>
   */
  com.clarifai.grpc.api.App getApps(int index);
  /**
   * <code>repeated .clarifai.api.App apps = 2;</code>
   */
  int getAppsCount();
  /**
   * <code>repeated .clarifai.api.App apps = 2;</code>
   */
  java.util.List<? extends com.clarifai.grpc.api.AppOrBuilder> 
      getAppsOrBuilderList();
  /**
   * <code>repeated .clarifai.api.App apps = 2;</code>
   */
  com.clarifai.grpc.api.AppOrBuilder getAppsOrBuilder(
      int index);

  /**
   * <pre>
   * The action to perform on the patched App objects
   * Supported values: 'overwrite' and 'remove'.
   * Note that 'remove' can only be used to remove the app image by setting
   * 'image.url' in the request to the current value returned for that app.
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * The action to perform on the patched App objects
   * Supported values: 'overwrite' and 'remove'.
   * Note that 'remove' can only be used to remove the app image by setting
   * 'image.url' in the request to the current value returned for that app.
   * </pre>
   *
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();
}
