// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface PipelineVersionRunStatusLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.PipelineVersionRunStatusLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique ID for this status record
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique ID for this status record
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The PipelineVersionRun this log entry belongs to
   * </pre>
   *
   * <code>string pipeline_version_run_id = 2;</code>
   * @return The pipelineVersionRunId.
   */
  java.lang.String getPipelineVersionRunId();
  /**
   * <pre>
   * The PipelineVersionRun this log entry belongs to
   * </pre>
   *
   * <code>string pipeline_version_run_id = 2;</code>
   * @return The bytes for pipelineVersionRunId.
   */
  com.google.protobuf.ByteString
      getPipelineVersionRunIdBytes();

  /**
   * <pre>
   * Clarifai status object representing the current status
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 3;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Clarifai status object representing the current status
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 3;</code>
   * @return The status.
   */
  com.clarifai.grpc.api.status.Status getStatus();
  /**
   * <pre>
   * Clarifai status object representing the current status
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 3;</code>
   */
  com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder();

  /**
   * <pre>
   * Optional human-readable reason or message (e.g. "Paused due to resource limit")
   * </pre>
   *
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Optional human-readable reason or message (e.g. "Paused due to resource limit")
   * </pre>
   *
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Who triggered this status change
   * </pre>
   *
   * <code>string triggered_by_user_id = 5;</code>
   * @return The triggeredByUserId.
   */
  java.lang.String getTriggeredByUserId();
  /**
   * <pre>
   * Who triggered this status change
   * </pre>
   *
   * <code>string triggered_by_user_id = 5;</code>
   * @return The bytes for triggeredByUserId.
   */
  com.google.protobuf.ByteString
      getTriggeredByUserIdBytes();

  /**
   * <pre>
   * When this status was recorded
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * When this status was recorded
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * When this status was recorded
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
}
