// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

/**
 * Protobuf type {@code clarifai.api.PostPipelineStepVersionsUploadConfig}
 */
public final class PostPipelineStepVersionsUploadConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clarifai.api.PostPipelineStepVersionsUploadConfig)
    PostPipelineStepVersionsUploadConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PostPipelineStepVersionsUploadConfig.newBuilder() to construct.
  private PostPipelineStepVersionsUploadConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PostPipelineStepVersionsUploadConfig() {
    pipelineStepId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PostPipelineStepVersionsUploadConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PostPipelineStepVersionsUploadConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.clarifai.grpc.api.UserAppIDSet.Builder subBuilder = null;
            if (userAppId_ != null) {
              subBuilder = userAppId_.toBuilder();
            }
            userAppId_ = input.readMessage(com.clarifai.grpc.api.UserAppIDSet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userAppId_);
              userAppId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            pipelineStepId_ = s;
            break;
          }
          case 26: {
            com.clarifai.grpc.api.PipelineStepVersion.Builder subBuilder = null;
            if (pipelineStepVersion_ != null) {
              subBuilder = pipelineStepVersion_.toBuilder();
            }
            pipelineStepVersion_ = input.readMessage(com.clarifai.grpc.api.PipelineStepVersion.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pipelineStepVersion_);
              pipelineStepVersion_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            totalSize_ = input.readUInt64();
            break;
          }
          case 40: {

            storageRequestSize_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PostPipelineStepVersionsUploadConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PostPipelineStepVersionsUploadConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.class, com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.Builder.class);
  }

  public static final int USER_APP_ID_FIELD_NUMBER = 1;
  private com.clarifai.grpc.api.UserAppIDSet userAppId_;
  /**
   * <pre>
   * User ID and App ID of the user uploading the pipeline step
   * </pre>
   *
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return Whether the userAppId field is set.
   */
  @java.lang.Override
  public boolean hasUserAppId() {
    return userAppId_ != null;
  }
  /**
   * <pre>
   * User ID and App ID of the user uploading the pipeline step
   * </pre>
   *
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return The userAppId.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.UserAppIDSet getUserAppId() {
    return userAppId_ == null ? com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
  }
  /**
   * <pre>
   * User ID and App ID of the user uploading the pipeline step
   * </pre>
   *
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
    return getUserAppId();
  }

  public static final int PIPELINE_STEP_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object pipelineStepId_;
  /**
   * <pre>
   * Pipeline Step to create version for
   * </pre>
   *
   * <code>string pipeline_step_id = 2;</code>
   * @return The pipelineStepId.
   */
  @java.lang.Override
  public java.lang.String getPipelineStepId() {
    java.lang.Object ref = pipelineStepId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pipelineStepId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pipeline Step to create version for
   * </pre>
   *
   * <code>string pipeline_step_id = 2;</code>
   * @return The bytes for pipelineStepId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPipelineStepIdBytes() {
    java.lang.Object ref = pipelineStepId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pipelineStepId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIPELINE_STEP_VERSION_FIELD_NUMBER = 3;
  private com.clarifai.grpc.api.PipelineStepVersion pipelineStepVersion_;
  /**
   * <pre>
   * Specification for the pipeline step version to be uploaded
   * </pre>
   *
   * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
   * @return Whether the pipelineStepVersion field is set.
   */
  @java.lang.Override
  public boolean hasPipelineStepVersion() {
    return pipelineStepVersion_ != null;
  }
  /**
   * <pre>
   * Specification for the pipeline step version to be uploaded
   * </pre>
   *
   * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
   * @return The pipelineStepVersion.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.PipelineStepVersion getPipelineStepVersion() {
    return pipelineStepVersion_ == null ? com.clarifai.grpc.api.PipelineStepVersion.getDefaultInstance() : pipelineStepVersion_;
  }
  /**
   * <pre>
   * Specification for the pipeline step version to be uploaded
   * </pre>
   *
   * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.PipelineStepVersionOrBuilder getPipelineStepVersionOrBuilder() {
    return getPipelineStepVersion();
  }

  public static final int TOTAL_SIZE_FIELD_NUMBER = 4;
  private long totalSize_;
  /**
   * <pre>
   * Number of bytes in the pipeline step files to be uploaded
   * </pre>
   *
   * <code>uint64 total_size = 4;</code>
   * @return The totalSize.
   */
  @java.lang.Override
  public long getTotalSize() {
    return totalSize_;
  }

  public static final int STORAGE_REQUEST_SIZE_FIELD_NUMBER = 5;
  private long storageRequestSize_;
  /**
   * <pre>
   * Number of bytes requested for the build process.
   * </pre>
   *
   * <code>uint64 storage_request_size = 5;</code>
   * @return The storageRequestSize.
   */
  @java.lang.Override
  public long getStorageRequestSize() {
    return storageRequestSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userAppId_ != null) {
      output.writeMessage(1, getUserAppId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineStepId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pipelineStepId_);
    }
    if (pipelineStepVersion_ != null) {
      output.writeMessage(3, getPipelineStepVersion());
    }
    if (totalSize_ != 0L) {
      output.writeUInt64(4, totalSize_);
    }
    if (storageRequestSize_ != 0L) {
      output.writeUInt64(5, storageRequestSize_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userAppId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserAppId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineStepId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pipelineStepId_);
    }
    if (pipelineStepVersion_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPipelineStepVersion());
    }
    if (totalSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, totalSize_);
    }
    if (storageRequestSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, storageRequestSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig)) {
      return super.equals(obj);
    }
    com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig other = (com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig) obj;

    if (hasUserAppId() != other.hasUserAppId()) return false;
    if (hasUserAppId()) {
      if (!getUserAppId()
          .equals(other.getUserAppId())) return false;
    }
    if (!getPipelineStepId()
        .equals(other.getPipelineStepId())) return false;
    if (hasPipelineStepVersion() != other.hasPipelineStepVersion()) return false;
    if (hasPipelineStepVersion()) {
      if (!getPipelineStepVersion()
          .equals(other.getPipelineStepVersion())) return false;
    }
    if (getTotalSize()
        != other.getTotalSize()) return false;
    if (getStorageRequestSize()
        != other.getStorageRequestSize()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserAppId()) {
      hash = (37 * hash) + USER_APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserAppId().hashCode();
    }
    hash = (37 * hash) + PIPELINE_STEP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPipelineStepId().hashCode();
    if (hasPipelineStepVersion()) {
      hash = (37 * hash) + PIPELINE_STEP_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getPipelineStepVersion().hashCode();
    }
    hash = (37 * hash) + TOTAL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalSize());
    hash = (37 * hash) + STORAGE_REQUEST_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStorageRequestSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clarifai.api.PostPipelineStepVersionsUploadConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clarifai.api.PostPipelineStepVersionsUploadConfig)
      com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PostPipelineStepVersionsUploadConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PostPipelineStepVersionsUploadConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.class, com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.Builder.class);
    }

    // Construct using com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userAppIdBuilder_ == null) {
        userAppId_ = null;
      } else {
        userAppId_ = null;
        userAppIdBuilder_ = null;
      }
      pipelineStepId_ = "";

      if (pipelineStepVersionBuilder_ == null) {
        pipelineStepVersion_ = null;
      } else {
        pipelineStepVersion_ = null;
        pipelineStepVersionBuilder_ = null;
      }
      totalSize_ = 0L;

      storageRequestSize_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PostPipelineStepVersionsUploadConfig_descriptor;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig getDefaultInstanceForType() {
      return com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.getDefaultInstance();
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig build() {
      com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig buildPartial() {
      com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig result = new com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig(this);
      if (userAppIdBuilder_ == null) {
        result.userAppId_ = userAppId_;
      } else {
        result.userAppId_ = userAppIdBuilder_.build();
      }
      result.pipelineStepId_ = pipelineStepId_;
      if (pipelineStepVersionBuilder_ == null) {
        result.pipelineStepVersion_ = pipelineStepVersion_;
      } else {
        result.pipelineStepVersion_ = pipelineStepVersionBuilder_.build();
      }
      result.totalSize_ = totalSize_;
      result.storageRequestSize_ = storageRequestSize_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig) {
        return mergeFrom((com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig other) {
      if (other == com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig.getDefaultInstance()) return this;
      if (other.hasUserAppId()) {
        mergeUserAppId(other.getUserAppId());
      }
      if (!other.getPipelineStepId().isEmpty()) {
        pipelineStepId_ = other.pipelineStepId_;
        onChanged();
      }
      if (other.hasPipelineStepVersion()) {
        mergePipelineStepVersion(other.getPipelineStepVersion());
      }
      if (other.getTotalSize() != 0L) {
        setTotalSize(other.getTotalSize());
      }
      if (other.getStorageRequestSize() != 0L) {
        setStorageRequestSize(other.getStorageRequestSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.clarifai.grpc.api.UserAppIDSet userAppId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder> userAppIdBuilder_;
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return Whether the userAppId field is set.
     */
    public boolean hasUserAppId() {
      return userAppIdBuilder_ != null || userAppId_ != null;
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return The userAppId.
     */
    public com.clarifai.grpc.api.UserAppIDSet getUserAppId() {
      if (userAppIdBuilder_ == null) {
        return userAppId_ == null ? com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
      } else {
        return userAppIdBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder setUserAppId(com.clarifai.grpc.api.UserAppIDSet value) {
      if (userAppIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userAppId_ = value;
        onChanged();
      } else {
        userAppIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder setUserAppId(
        com.clarifai.grpc.api.UserAppIDSet.Builder builderForValue) {
      if (userAppIdBuilder_ == null) {
        userAppId_ = builderForValue.build();
        onChanged();
      } else {
        userAppIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder mergeUserAppId(com.clarifai.grpc.api.UserAppIDSet value) {
      if (userAppIdBuilder_ == null) {
        if (userAppId_ != null) {
          userAppId_ =
            com.clarifai.grpc.api.UserAppIDSet.newBuilder(userAppId_).mergeFrom(value).buildPartial();
        } else {
          userAppId_ = value;
        }
        onChanged();
      } else {
        userAppIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder clearUserAppId() {
      if (userAppIdBuilder_ == null) {
        userAppId_ = null;
        onChanged();
      } else {
        userAppId_ = null;
        userAppIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public com.clarifai.grpc.api.UserAppIDSet.Builder getUserAppIdBuilder() {
      
      onChanged();
      return getUserAppIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
      if (userAppIdBuilder_ != null) {
        return userAppIdBuilder_.getMessageOrBuilder();
      } else {
        return userAppId_ == null ?
            com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
      }
    }
    /**
     * <pre>
     * User ID and App ID of the user uploading the pipeline step
     * </pre>
     *
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder> 
        getUserAppIdFieldBuilder() {
      if (userAppIdBuilder_ == null) {
        userAppIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder>(
                getUserAppId(),
                getParentForChildren(),
                isClean());
        userAppId_ = null;
      }
      return userAppIdBuilder_;
    }

    private java.lang.Object pipelineStepId_ = "";
    /**
     * <pre>
     * Pipeline Step to create version for
     * </pre>
     *
     * <code>string pipeline_step_id = 2;</code>
     * @return The pipelineStepId.
     */
    public java.lang.String getPipelineStepId() {
      java.lang.Object ref = pipelineStepId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipelineStepId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Pipeline Step to create version for
     * </pre>
     *
     * <code>string pipeline_step_id = 2;</code>
     * @return The bytes for pipelineStepId.
     */
    public com.google.protobuf.ByteString
        getPipelineStepIdBytes() {
      java.lang.Object ref = pipelineStepId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipelineStepId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pipeline Step to create version for
     * </pre>
     *
     * <code>string pipeline_step_id = 2;</code>
     * @param value The pipelineStepId to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineStepId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pipelineStepId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline Step to create version for
     * </pre>
     *
     * <code>string pipeline_step_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPipelineStepId() {
      
      pipelineStepId_ = getDefaultInstance().getPipelineStepId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline Step to create version for
     * </pre>
     *
     * <code>string pipeline_step_id = 2;</code>
     * @param value The bytes for pipelineStepId to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineStepIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pipelineStepId_ = value;
      onChanged();
      return this;
    }

    private com.clarifai.grpc.api.PipelineStepVersion pipelineStepVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.PipelineStepVersion, com.clarifai.grpc.api.PipelineStepVersion.Builder, com.clarifai.grpc.api.PipelineStepVersionOrBuilder> pipelineStepVersionBuilder_;
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     * @return Whether the pipelineStepVersion field is set.
     */
    public boolean hasPipelineStepVersion() {
      return pipelineStepVersionBuilder_ != null || pipelineStepVersion_ != null;
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     * @return The pipelineStepVersion.
     */
    public com.clarifai.grpc.api.PipelineStepVersion getPipelineStepVersion() {
      if (pipelineStepVersionBuilder_ == null) {
        return pipelineStepVersion_ == null ? com.clarifai.grpc.api.PipelineStepVersion.getDefaultInstance() : pipelineStepVersion_;
      } else {
        return pipelineStepVersionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public Builder setPipelineStepVersion(com.clarifai.grpc.api.PipelineStepVersion value) {
      if (pipelineStepVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pipelineStepVersion_ = value;
        onChanged();
      } else {
        pipelineStepVersionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public Builder setPipelineStepVersion(
        com.clarifai.grpc.api.PipelineStepVersion.Builder builderForValue) {
      if (pipelineStepVersionBuilder_ == null) {
        pipelineStepVersion_ = builderForValue.build();
        onChanged();
      } else {
        pipelineStepVersionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public Builder mergePipelineStepVersion(com.clarifai.grpc.api.PipelineStepVersion value) {
      if (pipelineStepVersionBuilder_ == null) {
        if (pipelineStepVersion_ != null) {
          pipelineStepVersion_ =
            com.clarifai.grpc.api.PipelineStepVersion.newBuilder(pipelineStepVersion_).mergeFrom(value).buildPartial();
        } else {
          pipelineStepVersion_ = value;
        }
        onChanged();
      } else {
        pipelineStepVersionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public Builder clearPipelineStepVersion() {
      if (pipelineStepVersionBuilder_ == null) {
        pipelineStepVersion_ = null;
        onChanged();
      } else {
        pipelineStepVersion_ = null;
        pipelineStepVersionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public com.clarifai.grpc.api.PipelineStepVersion.Builder getPipelineStepVersionBuilder() {
      
      onChanged();
      return getPipelineStepVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    public com.clarifai.grpc.api.PipelineStepVersionOrBuilder getPipelineStepVersionOrBuilder() {
      if (pipelineStepVersionBuilder_ != null) {
        return pipelineStepVersionBuilder_.getMessageOrBuilder();
      } else {
        return pipelineStepVersion_ == null ?
            com.clarifai.grpc.api.PipelineStepVersion.getDefaultInstance() : pipelineStepVersion_;
      }
    }
    /**
     * <pre>
     * Specification for the pipeline step version to be uploaded
     * </pre>
     *
     * <code>.clarifai.api.PipelineStepVersion pipeline_step_version = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.PipelineStepVersion, com.clarifai.grpc.api.PipelineStepVersion.Builder, com.clarifai.grpc.api.PipelineStepVersionOrBuilder> 
        getPipelineStepVersionFieldBuilder() {
      if (pipelineStepVersionBuilder_ == null) {
        pipelineStepVersionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.PipelineStepVersion, com.clarifai.grpc.api.PipelineStepVersion.Builder, com.clarifai.grpc.api.PipelineStepVersionOrBuilder>(
                getPipelineStepVersion(),
                getParentForChildren(),
                isClean());
        pipelineStepVersion_ = null;
      }
      return pipelineStepVersionBuilder_;
    }

    private long totalSize_ ;
    /**
     * <pre>
     * Number of bytes in the pipeline step files to be uploaded
     * </pre>
     *
     * <code>uint64 total_size = 4;</code>
     * @return The totalSize.
     */
    @java.lang.Override
    public long getTotalSize() {
      return totalSize_;
    }
    /**
     * <pre>
     * Number of bytes in the pipeline step files to be uploaded
     * </pre>
     *
     * <code>uint64 total_size = 4;</code>
     * @param value The totalSize to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSize(long value) {
      
      totalSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of bytes in the pipeline step files to be uploaded
     * </pre>
     *
     * <code>uint64 total_size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSize() {
      
      totalSize_ = 0L;
      onChanged();
      return this;
    }

    private long storageRequestSize_ ;
    /**
     * <pre>
     * Number of bytes requested for the build process.
     * </pre>
     *
     * <code>uint64 storage_request_size = 5;</code>
     * @return The storageRequestSize.
     */
    @java.lang.Override
    public long getStorageRequestSize() {
      return storageRequestSize_;
    }
    /**
     * <pre>
     * Number of bytes requested for the build process.
     * </pre>
     *
     * <code>uint64 storage_request_size = 5;</code>
     * @param value The storageRequestSize to set.
     * @return This builder for chaining.
     */
    public Builder setStorageRequestSize(long value) {
      
      storageRequestSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Number of bytes requested for the build process.
     * </pre>
     *
     * <code>uint64 storage_request_size = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStorageRequestSize() {
      
      storageRequestSize_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clarifai.api.PostPipelineStepVersionsUploadConfig)
  }

  // @@protoc_insertion_point(class_scope:clarifai.api.PostPipelineStepVersionsUploadConfig)
  private static final com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig();
  }

  public static com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PostPipelineStepVersionsUploadConfig>
      PARSER = new com.google.protobuf.AbstractParser<PostPipelineStepVersionsUploadConfig>() {
    @java.lang.Override
    public PostPipelineStepVersionsUploadConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PostPipelineStepVersionsUploadConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PostPipelineStepVersionsUploadConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PostPipelineStepVersionsUploadConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.clarifai.grpc.api.PostPipelineStepVersionsUploadConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

