// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

/**
 * <pre>
 * PutTaskAssignmentsRequest
 * </pre>
 *
 * Protobuf type {@code clarifai.api.PutTaskAssignmentsRequest}
 */
public final class PutTaskAssignmentsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clarifai.api.PutTaskAssignmentsRequest)
    PutTaskAssignmentsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PutTaskAssignmentsRequest.newBuilder() to construct.
  private PutTaskAssignmentsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PutTaskAssignmentsRequest() {
    taskId_ = "";
    inputId_ = "";
    action_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PutTaskAssignmentsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PutTaskAssignmentsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.clarifai.grpc.api.UserAppIDSet.Builder subBuilder = null;
            if (userAppId_ != null) {
              subBuilder = userAppId_.toBuilder();
            }
            userAppId_ = input.readMessage(com.clarifai.grpc.api.UserAppIDSet.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userAppId_);
              userAppId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            taskId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            inputId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            action_ = rawValue;
            break;
          }
          case 50: {
            com.clarifai.grpc.api.LabelSubmitConfig.Builder subBuilder = null;
            if (actionConfigCase_ == 6) {
              subBuilder = ((com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_).toBuilder();
            }
            actionConfig_ =
                input.readMessage(com.clarifai.grpc.api.LabelSubmitConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_);
              actionConfig_ = subBuilder.buildPartial();
            }
            actionConfigCase_ = 6;
            break;
          }
          case 58: {
            com.clarifai.grpc.api.ReviewApproveConfig.Builder subBuilder = null;
            if (actionConfigCase_ == 7) {
              subBuilder = ((com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_).toBuilder();
            }
            actionConfig_ =
                input.readMessage(com.clarifai.grpc.api.ReviewApproveConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_);
              actionConfig_ = subBuilder.buildPartial();
            }
            actionConfigCase_ = 7;
            break;
          }
          case 66: {
            com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder subBuilder = null;
            if (actionConfigCase_ == 8) {
              subBuilder = ((com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_).toBuilder();
            }
            actionConfig_ =
                input.readMessage(com.clarifai.grpc.api.ReviewRequestChangesConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_);
              actionConfig_ = subBuilder.buildPartial();
            }
            actionConfigCase_ = 8;
            break;
          }
          case 74: {
            com.clarifai.grpc.api.ReviewRejectConfig.Builder subBuilder = null;
            if (actionConfigCase_ == 9) {
              subBuilder = ((com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_).toBuilder();
            }
            actionConfig_ =
                input.readMessage(com.clarifai.grpc.api.ReviewRejectConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_);
              actionConfig_ = subBuilder.buildPartial();
            }
            actionConfigCase_ = 9;
            break;
          }
          case 82: {
            com.clarifai.grpc.api.ReviewStartConfig.Builder subBuilder = null;
            if (actionConfigCase_ == 10) {
              subBuilder = ((com.clarifai.grpc.api.ReviewStartConfig) actionConfig_).toBuilder();
            }
            actionConfig_ =
                input.readMessage(com.clarifai.grpc.api.ReviewStartConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.clarifai.grpc.api.ReviewStartConfig) actionConfig_);
              actionConfig_ = subBuilder.buildPartial();
            }
            actionConfigCase_ = 10;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PutTaskAssignmentsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PutTaskAssignmentsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clarifai.grpc.api.PutTaskAssignmentsRequest.class, com.clarifai.grpc.api.PutTaskAssignmentsRequest.Builder.class);
  }

  private int actionConfigCase_ = 0;
  private java.lang.Object actionConfig_;
  public enum ActionConfigCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LABEL_SUBMIT_CONFIG(6),
    REVIEW_START_CONFIG(10),
    REVIEW_APPROVE_CONFIG(7),
    REVIEW_REQUEST_CHANGES_CONFIG(8),
    REVIEW_REJECT_CONFIG(9),
    ACTIONCONFIG_NOT_SET(0);
    private final int value;
    private ActionConfigCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionConfigCase valueOf(int value) {
      return forNumber(value);
    }

    public static ActionConfigCase forNumber(int value) {
      switch (value) {
        case 6: return LABEL_SUBMIT_CONFIG;
        case 10: return REVIEW_START_CONFIG;
        case 7: return REVIEW_APPROVE_CONFIG;
        case 8: return REVIEW_REQUEST_CHANGES_CONFIG;
        case 9: return REVIEW_REJECT_CONFIG;
        case 0: return ACTIONCONFIG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ActionConfigCase
  getActionConfigCase() {
    return ActionConfigCase.forNumber(
        actionConfigCase_);
  }

  public static final int USER_APP_ID_FIELD_NUMBER = 1;
  private com.clarifai.grpc.api.UserAppIDSet userAppId_;
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return Whether the userAppId field is set.
   */
  @java.lang.Override
  public boolean hasUserAppId() {
    return userAppId_ != null;
  }
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   * @return The userAppId.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.UserAppIDSet getUserAppId() {
    return userAppId_ == null ? com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
  }
  /**
   * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
    return getUserAppId();
  }

  public static final int TASK_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object taskId_;
  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      taskId_ = s;
      return s;
    }
  }
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    java.lang.Object ref = taskId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      taskId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object inputId_;
  /**
   * <pre>
   * Deprecated: use action and action_config instead.
   * Supported for backwards compatibility: setting this field is equivalent with
   * * action = LABEL_SUBMIT
   * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
   * </pre>
   *
   * <code>string input_id = 3;</code>
   * @return The inputId.
   */
  @java.lang.Override
  public java.lang.String getInputId() {
    java.lang.Object ref = inputId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inputId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Deprecated: use action and action_config instead.
   * Supported for backwards compatibility: setting this field is equivalent with
   * * action = LABEL_SUBMIT
   * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
   * </pre>
   *
   * <code>string input_id = 3;</code>
   * @return The bytes for inputId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputIdBytes() {
    java.lang.Object ref = inputId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inputId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_FIELD_NUMBER = 4;
  private int action_;
  /**
   * <pre>
   * Action to perform on selected task.
   * </pre>
   *
   * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override public int getActionValue() {
    return action_;
  }
  /**
   * <pre>
   * Action to perform on selected task.
   * </pre>
   *
   * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
   * @return The action.
   */
  @java.lang.Override public com.clarifai.grpc.api.PutTaskAssignmentsRequestAction getAction() {
    @SuppressWarnings("deprecation")
    com.clarifai.grpc.api.PutTaskAssignmentsRequestAction result = com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.valueOf(action_);
    return result == null ? com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.UNRECOGNIZED : result;
  }

  public static final int LABEL_SUBMIT_CONFIG_FIELD_NUMBER = 6;
  /**
   * <pre>
   *    LabelStartConfig label_start_config = 5; // no config for label start action
   * </pre>
   *
   * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
   * @return Whether the labelSubmitConfig field is set.
   */
  @java.lang.Override
  public boolean hasLabelSubmitConfig() {
    return actionConfigCase_ == 6;
  }
  /**
   * <pre>
   *    LabelStartConfig label_start_config = 5; // no config for label start action
   * </pre>
   *
   * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
   * @return The labelSubmitConfig.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.LabelSubmitConfig getLabelSubmitConfig() {
    if (actionConfigCase_ == 6) {
       return (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
  }
  /**
   * <pre>
   *    LabelStartConfig label_start_config = 5; // no config for label start action
   * </pre>
   *
   * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.LabelSubmitConfigOrBuilder getLabelSubmitConfigOrBuilder() {
    if (actionConfigCase_ == 6) {
       return (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
  }

  public static final int REVIEW_START_CONFIG_FIELD_NUMBER = 10;
  /**
   * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
   * @return Whether the reviewStartConfig field is set.
   */
  @java.lang.Override
  public boolean hasReviewStartConfig() {
    return actionConfigCase_ == 10;
  }
  /**
   * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
   * @return The reviewStartConfig.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewStartConfig getReviewStartConfig() {
    if (actionConfigCase_ == 10) {
       return (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
  }
  /**
   * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewStartConfigOrBuilder getReviewStartConfigOrBuilder() {
    if (actionConfigCase_ == 10) {
       return (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
  }

  public static final int REVIEW_APPROVE_CONFIG_FIELD_NUMBER = 7;
  /**
   * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
   * @return Whether the reviewApproveConfig field is set.
   */
  @java.lang.Override
  public boolean hasReviewApproveConfig() {
    return actionConfigCase_ == 7;
  }
  /**
   * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
   * @return The reviewApproveConfig.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewApproveConfig getReviewApproveConfig() {
    if (actionConfigCase_ == 7) {
       return (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
  }
  /**
   * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewApproveConfigOrBuilder getReviewApproveConfigOrBuilder() {
    if (actionConfigCase_ == 7) {
       return (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
  }

  public static final int REVIEW_REQUEST_CHANGES_CONFIG_FIELD_NUMBER = 8;
  /**
   * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
   * @return Whether the reviewRequestChangesConfig field is set.
   */
  @java.lang.Override
  public boolean hasReviewRequestChangesConfig() {
    return actionConfigCase_ == 8;
  }
  /**
   * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
   * @return The reviewRequestChangesConfig.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewRequestChangesConfig getReviewRequestChangesConfig() {
    if (actionConfigCase_ == 8) {
       return (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
  }
  /**
   * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewRequestChangesConfigOrBuilder getReviewRequestChangesConfigOrBuilder() {
    if (actionConfigCase_ == 8) {
       return (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
  }

  public static final int REVIEW_REJECT_CONFIG_FIELD_NUMBER = 9;
  /**
   * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
   * @return Whether the reviewRejectConfig field is set.
   */
  @java.lang.Override
  public boolean hasReviewRejectConfig() {
    return actionConfigCase_ == 9;
  }
  /**
   * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
   * @return The reviewRejectConfig.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewRejectConfig getReviewRejectConfig() {
    if (actionConfigCase_ == 9) {
       return (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
  }
  /**
   * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.ReviewRejectConfigOrBuilder getReviewRejectConfigOrBuilder() {
    if (actionConfigCase_ == 9) {
       return (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_;
    }
    return com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userAppId_ != null) {
      output.writeMessage(1, getUserAppId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inputId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inputId_);
    }
    if (action_ != com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.PUT_TASK_ASSIGNMENTS_REQUEST_ACTION_NOT_SET.getNumber()) {
      output.writeEnum(4, action_);
    }
    if (actionConfigCase_ == 6) {
      output.writeMessage(6, (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_);
    }
    if (actionConfigCase_ == 7) {
      output.writeMessage(7, (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_);
    }
    if (actionConfigCase_ == 8) {
      output.writeMessage(8, (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_);
    }
    if (actionConfigCase_ == 9) {
      output.writeMessage(9, (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_);
    }
    if (actionConfigCase_ == 10) {
      output.writeMessage(10, (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userAppId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserAppId());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inputId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, inputId_);
    }
    if (action_ != com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.PUT_TASK_ASSIGNMENTS_REQUEST_ACTION_NOT_SET.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, action_);
    }
    if (actionConfigCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_);
    }
    if (actionConfigCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_);
    }
    if (actionConfigCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_);
    }
    if (actionConfigCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_);
    }
    if (actionConfigCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.clarifai.grpc.api.PutTaskAssignmentsRequest)) {
      return super.equals(obj);
    }
    com.clarifai.grpc.api.PutTaskAssignmentsRequest other = (com.clarifai.grpc.api.PutTaskAssignmentsRequest) obj;

    if (hasUserAppId() != other.hasUserAppId()) return false;
    if (hasUserAppId()) {
      if (!getUserAppId()
          .equals(other.getUserAppId())) return false;
    }
    if (!getTaskId()
        .equals(other.getTaskId())) return false;
    if (!getInputId()
        .equals(other.getInputId())) return false;
    if (action_ != other.action_) return false;
    if (!getActionConfigCase().equals(other.getActionConfigCase())) return false;
    switch (actionConfigCase_) {
      case 6:
        if (!getLabelSubmitConfig()
            .equals(other.getLabelSubmitConfig())) return false;
        break;
      case 10:
        if (!getReviewStartConfig()
            .equals(other.getReviewStartConfig())) return false;
        break;
      case 7:
        if (!getReviewApproveConfig()
            .equals(other.getReviewApproveConfig())) return false;
        break;
      case 8:
        if (!getReviewRequestChangesConfig()
            .equals(other.getReviewRequestChangesConfig())) return false;
        break;
      case 9:
        if (!getReviewRejectConfig()
            .equals(other.getReviewRejectConfig())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserAppId()) {
      hash = (37 * hash) + USER_APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserAppId().hashCode();
    }
    hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId().hashCode();
    hash = (37 * hash) + INPUT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInputId().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    switch (actionConfigCase_) {
      case 6:
        hash = (37 * hash) + LABEL_SUBMIT_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getLabelSubmitConfig().hashCode();
        break;
      case 10:
        hash = (37 * hash) + REVIEW_START_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getReviewStartConfig().hashCode();
        break;
      case 7:
        hash = (37 * hash) + REVIEW_APPROVE_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getReviewApproveConfig().hashCode();
        break;
      case 8:
        hash = (37 * hash) + REVIEW_REQUEST_CHANGES_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getReviewRequestChangesConfig().hashCode();
        break;
      case 9:
        hash = (37 * hash) + REVIEW_REJECT_CONFIG_FIELD_NUMBER;
        hash = (53 * hash) + getReviewRejectConfig().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clarifai.grpc.api.PutTaskAssignmentsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * PutTaskAssignmentsRequest
   * </pre>
   *
   * Protobuf type {@code clarifai.api.PutTaskAssignmentsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clarifai.api.PutTaskAssignmentsRequest)
      com.clarifai.grpc.api.PutTaskAssignmentsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PutTaskAssignmentsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PutTaskAssignmentsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clarifai.grpc.api.PutTaskAssignmentsRequest.class, com.clarifai.grpc.api.PutTaskAssignmentsRequest.Builder.class);
    }

    // Construct using com.clarifai.grpc.api.PutTaskAssignmentsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userAppIdBuilder_ == null) {
        userAppId_ = null;
      } else {
        userAppId_ = null;
        userAppIdBuilder_ = null;
      }
      taskId_ = "";

      inputId_ = "";

      action_ = 0;

      actionConfigCase_ = 0;
      actionConfig_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_PutTaskAssignmentsRequest_descriptor;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PutTaskAssignmentsRequest getDefaultInstanceForType() {
      return com.clarifai.grpc.api.PutTaskAssignmentsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PutTaskAssignmentsRequest build() {
      com.clarifai.grpc.api.PutTaskAssignmentsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.PutTaskAssignmentsRequest buildPartial() {
      com.clarifai.grpc.api.PutTaskAssignmentsRequest result = new com.clarifai.grpc.api.PutTaskAssignmentsRequest(this);
      if (userAppIdBuilder_ == null) {
        result.userAppId_ = userAppId_;
      } else {
        result.userAppId_ = userAppIdBuilder_.build();
      }
      result.taskId_ = taskId_;
      result.inputId_ = inputId_;
      result.action_ = action_;
      if (actionConfigCase_ == 6) {
        if (labelSubmitConfigBuilder_ == null) {
          result.actionConfig_ = actionConfig_;
        } else {
          result.actionConfig_ = labelSubmitConfigBuilder_.build();
        }
      }
      if (actionConfigCase_ == 10) {
        if (reviewStartConfigBuilder_ == null) {
          result.actionConfig_ = actionConfig_;
        } else {
          result.actionConfig_ = reviewStartConfigBuilder_.build();
        }
      }
      if (actionConfigCase_ == 7) {
        if (reviewApproveConfigBuilder_ == null) {
          result.actionConfig_ = actionConfig_;
        } else {
          result.actionConfig_ = reviewApproveConfigBuilder_.build();
        }
      }
      if (actionConfigCase_ == 8) {
        if (reviewRequestChangesConfigBuilder_ == null) {
          result.actionConfig_ = actionConfig_;
        } else {
          result.actionConfig_ = reviewRequestChangesConfigBuilder_.build();
        }
      }
      if (actionConfigCase_ == 9) {
        if (reviewRejectConfigBuilder_ == null) {
          result.actionConfig_ = actionConfig_;
        } else {
          result.actionConfig_ = reviewRejectConfigBuilder_.build();
        }
      }
      result.actionConfigCase_ = actionConfigCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clarifai.grpc.api.PutTaskAssignmentsRequest) {
        return mergeFrom((com.clarifai.grpc.api.PutTaskAssignmentsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clarifai.grpc.api.PutTaskAssignmentsRequest other) {
      if (other == com.clarifai.grpc.api.PutTaskAssignmentsRequest.getDefaultInstance()) return this;
      if (other.hasUserAppId()) {
        mergeUserAppId(other.getUserAppId());
      }
      if (!other.getTaskId().isEmpty()) {
        taskId_ = other.taskId_;
        onChanged();
      }
      if (!other.getInputId().isEmpty()) {
        inputId_ = other.inputId_;
        onChanged();
      }
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      switch (other.getActionConfigCase()) {
        case LABEL_SUBMIT_CONFIG: {
          mergeLabelSubmitConfig(other.getLabelSubmitConfig());
          break;
        }
        case REVIEW_START_CONFIG: {
          mergeReviewStartConfig(other.getReviewStartConfig());
          break;
        }
        case REVIEW_APPROVE_CONFIG: {
          mergeReviewApproveConfig(other.getReviewApproveConfig());
          break;
        }
        case REVIEW_REQUEST_CHANGES_CONFIG: {
          mergeReviewRequestChangesConfig(other.getReviewRequestChangesConfig());
          break;
        }
        case REVIEW_REJECT_CONFIG: {
          mergeReviewRejectConfig(other.getReviewRejectConfig());
          break;
        }
        case ACTIONCONFIG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clarifai.grpc.api.PutTaskAssignmentsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clarifai.grpc.api.PutTaskAssignmentsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int actionConfigCase_ = 0;
    private java.lang.Object actionConfig_;
    public ActionConfigCase
        getActionConfigCase() {
      return ActionConfigCase.forNumber(
          actionConfigCase_);
    }

    public Builder clearActionConfig() {
      actionConfigCase_ = 0;
      actionConfig_ = null;
      onChanged();
      return this;
    }


    private com.clarifai.grpc.api.UserAppIDSet userAppId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder> userAppIdBuilder_;
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return Whether the userAppId field is set.
     */
    public boolean hasUserAppId() {
      return userAppIdBuilder_ != null || userAppId_ != null;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     * @return The userAppId.
     */
    public com.clarifai.grpc.api.UserAppIDSet getUserAppId() {
      if (userAppIdBuilder_ == null) {
        return userAppId_ == null ? com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
      } else {
        return userAppIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder setUserAppId(com.clarifai.grpc.api.UserAppIDSet value) {
      if (userAppIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userAppId_ = value;
        onChanged();
      } else {
        userAppIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder setUserAppId(
        com.clarifai.grpc.api.UserAppIDSet.Builder builderForValue) {
      if (userAppIdBuilder_ == null) {
        userAppId_ = builderForValue.build();
        onChanged();
      } else {
        userAppIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder mergeUserAppId(com.clarifai.grpc.api.UserAppIDSet value) {
      if (userAppIdBuilder_ == null) {
        if (userAppId_ != null) {
          userAppId_ =
            com.clarifai.grpc.api.UserAppIDSet.newBuilder(userAppId_).mergeFrom(value).buildPartial();
        } else {
          userAppId_ = value;
        }
        onChanged();
      } else {
        userAppIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public Builder clearUserAppId() {
      if (userAppIdBuilder_ == null) {
        userAppId_ = null;
        onChanged();
      } else {
        userAppId_ = null;
        userAppIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public com.clarifai.grpc.api.UserAppIDSet.Builder getUserAppIdBuilder() {
      
      onChanged();
      return getUserAppIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    public com.clarifai.grpc.api.UserAppIDSetOrBuilder getUserAppIdOrBuilder() {
      if (userAppIdBuilder_ != null) {
        return userAppIdBuilder_.getMessageOrBuilder();
      } else {
        return userAppId_ == null ?
            com.clarifai.grpc.api.UserAppIDSet.getDefaultInstance() : userAppId_;
      }
    }
    /**
     * <code>.clarifai.api.UserAppIDSet user_app_id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder> 
        getUserAppIdFieldBuilder() {
      if (userAppIdBuilder_ == null) {
        userAppIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.UserAppIDSet, com.clarifai.grpc.api.UserAppIDSet.Builder, com.clarifai.grpc.api.UserAppIDSetOrBuilder>(
                getUserAppId(),
                getParentForChildren(),
                isClean());
        userAppId_ = null;
      }
      return userAppIdBuilder_;
    }

    private java.lang.Object taskId_ = "";
    /**
     * <code>string task_id = 2;</code>
     * @return The taskId.
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string task_id = 2;</code>
     * @return The bytes for taskId.
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      
      taskId_ = getDefaultInstance().getTaskId();
      onChanged();
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      taskId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inputId_ = "";
    /**
     * <pre>
     * Deprecated: use action and action_config instead.
     * Supported for backwards compatibility: setting this field is equivalent with
     * * action = LABEL_SUBMIT
     * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
     * </pre>
     *
     * <code>string input_id = 3;</code>
     * @return The inputId.
     */
    public java.lang.String getInputId() {
      java.lang.Object ref = inputId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inputId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Deprecated: use action and action_config instead.
     * Supported for backwards compatibility: setting this field is equivalent with
     * * action = LABEL_SUBMIT
     * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
     * </pre>
     *
     * <code>string input_id = 3;</code>
     * @return The bytes for inputId.
     */
    public com.google.protobuf.ByteString
        getInputIdBytes() {
      java.lang.Object ref = inputId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inputId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Deprecated: use action and action_config instead.
     * Supported for backwards compatibility: setting this field is equivalent with
     * * action = LABEL_SUBMIT
     * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
     * </pre>
     *
     * <code>string input_id = 3;</code>
     * @param value The inputId to set.
     * @return This builder for chaining.
     */
    public Builder setInputId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inputId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated: use action and action_config instead.
     * Supported for backwards compatibility: setting this field is equivalent with
     * * action = LABEL_SUBMIT
     * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
     * </pre>
     *
     * <code>string input_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputId() {
      
      inputId_ = getDefaultInstance().getInputId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Deprecated: use action and action_config instead.
     * Supported for backwards compatibility: setting this field is equivalent with
     * * action = LABEL_SUBMIT
     * * label_submit_config = [{"task_assignments": {{"id": "&lt;task-assignment-id-for-input-id&gt;"}}]
     * </pre>
     *
     * <code>string input_id = 3;</code>
     * @param value The bytes for inputId to set.
     * @return This builder for chaining.
     */
    public Builder setInputIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inputId_ = value;
      onChanged();
      return this;
    }

    private int action_ = 0;
    /**
     * <pre>
     * Action to perform on selected task.
     * </pre>
     *
     * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <pre>
     * Action to perform on selected task.
     * </pre>
     *
     * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Action to perform on selected task.
     * </pre>
     *
     * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.PutTaskAssignmentsRequestAction getAction() {
      @SuppressWarnings("deprecation")
      com.clarifai.grpc.api.PutTaskAssignmentsRequestAction result = com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.valueOf(action_);
      return result == null ? com.clarifai.grpc.api.PutTaskAssignmentsRequestAction.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Action to perform on selected task.
     * </pre>
     *
     * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(com.clarifai.grpc.api.PutTaskAssignmentsRequestAction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Action to perform on selected task.
     * </pre>
     *
     * <code>.clarifai.api.PutTaskAssignmentsRequestAction action = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.LabelSubmitConfig, com.clarifai.grpc.api.LabelSubmitConfig.Builder, com.clarifai.grpc.api.LabelSubmitConfigOrBuilder> labelSubmitConfigBuilder_;
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     * @return Whether the labelSubmitConfig field is set.
     */
    @java.lang.Override
    public boolean hasLabelSubmitConfig() {
      return actionConfigCase_ == 6;
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     * @return The labelSubmitConfig.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.LabelSubmitConfig getLabelSubmitConfig() {
      if (labelSubmitConfigBuilder_ == null) {
        if (actionConfigCase_ == 6) {
          return (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
      } else {
        if (actionConfigCase_ == 6) {
          return labelSubmitConfigBuilder_.getMessage();
        }
        return com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
      }
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    public Builder setLabelSubmitConfig(com.clarifai.grpc.api.LabelSubmitConfig value) {
      if (labelSubmitConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionConfig_ = value;
        onChanged();
      } else {
        labelSubmitConfigBuilder_.setMessage(value);
      }
      actionConfigCase_ = 6;
      return this;
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    public Builder setLabelSubmitConfig(
        com.clarifai.grpc.api.LabelSubmitConfig.Builder builderForValue) {
      if (labelSubmitConfigBuilder_ == null) {
        actionConfig_ = builderForValue.build();
        onChanged();
      } else {
        labelSubmitConfigBuilder_.setMessage(builderForValue.build());
      }
      actionConfigCase_ = 6;
      return this;
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    public Builder mergeLabelSubmitConfig(com.clarifai.grpc.api.LabelSubmitConfig value) {
      if (labelSubmitConfigBuilder_ == null) {
        if (actionConfigCase_ == 6 &&
            actionConfig_ != com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance()) {
          actionConfig_ = com.clarifai.grpc.api.LabelSubmitConfig.newBuilder((com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_)
              .mergeFrom(value).buildPartial();
        } else {
          actionConfig_ = value;
        }
        onChanged();
      } else {
        if (actionConfigCase_ == 6) {
          labelSubmitConfigBuilder_.mergeFrom(value);
        } else {
          labelSubmitConfigBuilder_.setMessage(value);
        }
      }
      actionConfigCase_ = 6;
      return this;
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    public Builder clearLabelSubmitConfig() {
      if (labelSubmitConfigBuilder_ == null) {
        if (actionConfigCase_ == 6) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
          onChanged();
        }
      } else {
        if (actionConfigCase_ == 6) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
        }
        labelSubmitConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    public com.clarifai.grpc.api.LabelSubmitConfig.Builder getLabelSubmitConfigBuilder() {
      return getLabelSubmitConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    @java.lang.Override
    public com.clarifai.grpc.api.LabelSubmitConfigOrBuilder getLabelSubmitConfigOrBuilder() {
      if ((actionConfigCase_ == 6) && (labelSubmitConfigBuilder_ != null)) {
        return labelSubmitConfigBuilder_.getMessageOrBuilder();
      } else {
        if (actionConfigCase_ == 6) {
          return (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
      }
    }
    /**
     * <pre>
     *    LabelStartConfig label_start_config = 5; // no config for label start action
     * </pre>
     *
     * <code>.clarifai.api.LabelSubmitConfig label_submit_config = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.LabelSubmitConfig, com.clarifai.grpc.api.LabelSubmitConfig.Builder, com.clarifai.grpc.api.LabelSubmitConfigOrBuilder> 
        getLabelSubmitConfigFieldBuilder() {
      if (labelSubmitConfigBuilder_ == null) {
        if (!(actionConfigCase_ == 6)) {
          actionConfig_ = com.clarifai.grpc.api.LabelSubmitConfig.getDefaultInstance();
        }
        labelSubmitConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.LabelSubmitConfig, com.clarifai.grpc.api.LabelSubmitConfig.Builder, com.clarifai.grpc.api.LabelSubmitConfigOrBuilder>(
                (com.clarifai.grpc.api.LabelSubmitConfig) actionConfig_,
                getParentForChildren(),
                isClean());
        actionConfig_ = null;
      }
      actionConfigCase_ = 6;
      onChanged();;
      return labelSubmitConfigBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewStartConfig, com.clarifai.grpc.api.ReviewStartConfig.Builder, com.clarifai.grpc.api.ReviewStartConfigOrBuilder> reviewStartConfigBuilder_;
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     * @return Whether the reviewStartConfig field is set.
     */
    @java.lang.Override
    public boolean hasReviewStartConfig() {
      return actionConfigCase_ == 10;
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     * @return The reviewStartConfig.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewStartConfig getReviewStartConfig() {
      if (reviewStartConfigBuilder_ == null) {
        if (actionConfigCase_ == 10) {
          return (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
      } else {
        if (actionConfigCase_ == 10) {
          return reviewStartConfigBuilder_.getMessage();
        }
        return com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    public Builder setReviewStartConfig(com.clarifai.grpc.api.ReviewStartConfig value) {
      if (reviewStartConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionConfig_ = value;
        onChanged();
      } else {
        reviewStartConfigBuilder_.setMessage(value);
      }
      actionConfigCase_ = 10;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    public Builder setReviewStartConfig(
        com.clarifai.grpc.api.ReviewStartConfig.Builder builderForValue) {
      if (reviewStartConfigBuilder_ == null) {
        actionConfig_ = builderForValue.build();
        onChanged();
      } else {
        reviewStartConfigBuilder_.setMessage(builderForValue.build());
      }
      actionConfigCase_ = 10;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    public Builder mergeReviewStartConfig(com.clarifai.grpc.api.ReviewStartConfig value) {
      if (reviewStartConfigBuilder_ == null) {
        if (actionConfigCase_ == 10 &&
            actionConfig_ != com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance()) {
          actionConfig_ = com.clarifai.grpc.api.ReviewStartConfig.newBuilder((com.clarifai.grpc.api.ReviewStartConfig) actionConfig_)
              .mergeFrom(value).buildPartial();
        } else {
          actionConfig_ = value;
        }
        onChanged();
      } else {
        if (actionConfigCase_ == 10) {
          reviewStartConfigBuilder_.mergeFrom(value);
        } else {
          reviewStartConfigBuilder_.setMessage(value);
        }
      }
      actionConfigCase_ = 10;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    public Builder clearReviewStartConfig() {
      if (reviewStartConfigBuilder_ == null) {
        if (actionConfigCase_ == 10) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
          onChanged();
        }
      } else {
        if (actionConfigCase_ == 10) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
        }
        reviewStartConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    public com.clarifai.grpc.api.ReviewStartConfig.Builder getReviewStartConfigBuilder() {
      return getReviewStartConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewStartConfigOrBuilder getReviewStartConfigOrBuilder() {
      if ((actionConfigCase_ == 10) && (reviewStartConfigBuilder_ != null)) {
        return reviewStartConfigBuilder_.getMessageOrBuilder();
      } else {
        if (actionConfigCase_ == 10) {
          return (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewStartConfig review_start_config = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewStartConfig, com.clarifai.grpc.api.ReviewStartConfig.Builder, com.clarifai.grpc.api.ReviewStartConfigOrBuilder> 
        getReviewStartConfigFieldBuilder() {
      if (reviewStartConfigBuilder_ == null) {
        if (!(actionConfigCase_ == 10)) {
          actionConfig_ = com.clarifai.grpc.api.ReviewStartConfig.getDefaultInstance();
        }
        reviewStartConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.ReviewStartConfig, com.clarifai.grpc.api.ReviewStartConfig.Builder, com.clarifai.grpc.api.ReviewStartConfigOrBuilder>(
                (com.clarifai.grpc.api.ReviewStartConfig) actionConfig_,
                getParentForChildren(),
                isClean());
        actionConfig_ = null;
      }
      actionConfigCase_ = 10;
      onChanged();;
      return reviewStartConfigBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewApproveConfig, com.clarifai.grpc.api.ReviewApproveConfig.Builder, com.clarifai.grpc.api.ReviewApproveConfigOrBuilder> reviewApproveConfigBuilder_;
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     * @return Whether the reviewApproveConfig field is set.
     */
    @java.lang.Override
    public boolean hasReviewApproveConfig() {
      return actionConfigCase_ == 7;
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     * @return The reviewApproveConfig.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewApproveConfig getReviewApproveConfig() {
      if (reviewApproveConfigBuilder_ == null) {
        if (actionConfigCase_ == 7) {
          return (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
      } else {
        if (actionConfigCase_ == 7) {
          return reviewApproveConfigBuilder_.getMessage();
        }
        return com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    public Builder setReviewApproveConfig(com.clarifai.grpc.api.ReviewApproveConfig value) {
      if (reviewApproveConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionConfig_ = value;
        onChanged();
      } else {
        reviewApproveConfigBuilder_.setMessage(value);
      }
      actionConfigCase_ = 7;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    public Builder setReviewApproveConfig(
        com.clarifai.grpc.api.ReviewApproveConfig.Builder builderForValue) {
      if (reviewApproveConfigBuilder_ == null) {
        actionConfig_ = builderForValue.build();
        onChanged();
      } else {
        reviewApproveConfigBuilder_.setMessage(builderForValue.build());
      }
      actionConfigCase_ = 7;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    public Builder mergeReviewApproveConfig(com.clarifai.grpc.api.ReviewApproveConfig value) {
      if (reviewApproveConfigBuilder_ == null) {
        if (actionConfigCase_ == 7 &&
            actionConfig_ != com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance()) {
          actionConfig_ = com.clarifai.grpc.api.ReviewApproveConfig.newBuilder((com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_)
              .mergeFrom(value).buildPartial();
        } else {
          actionConfig_ = value;
        }
        onChanged();
      } else {
        if (actionConfigCase_ == 7) {
          reviewApproveConfigBuilder_.mergeFrom(value);
        } else {
          reviewApproveConfigBuilder_.setMessage(value);
        }
      }
      actionConfigCase_ = 7;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    public Builder clearReviewApproveConfig() {
      if (reviewApproveConfigBuilder_ == null) {
        if (actionConfigCase_ == 7) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
          onChanged();
        }
      } else {
        if (actionConfigCase_ == 7) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
        }
        reviewApproveConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    public com.clarifai.grpc.api.ReviewApproveConfig.Builder getReviewApproveConfigBuilder() {
      return getReviewApproveConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewApproveConfigOrBuilder getReviewApproveConfigOrBuilder() {
      if ((actionConfigCase_ == 7) && (reviewApproveConfigBuilder_ != null)) {
        return reviewApproveConfigBuilder_.getMessageOrBuilder();
      } else {
        if (actionConfigCase_ == 7) {
          return (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewApproveConfig review_approve_config = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewApproveConfig, com.clarifai.grpc.api.ReviewApproveConfig.Builder, com.clarifai.grpc.api.ReviewApproveConfigOrBuilder> 
        getReviewApproveConfigFieldBuilder() {
      if (reviewApproveConfigBuilder_ == null) {
        if (!(actionConfigCase_ == 7)) {
          actionConfig_ = com.clarifai.grpc.api.ReviewApproveConfig.getDefaultInstance();
        }
        reviewApproveConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.ReviewApproveConfig, com.clarifai.grpc.api.ReviewApproveConfig.Builder, com.clarifai.grpc.api.ReviewApproveConfigOrBuilder>(
                (com.clarifai.grpc.api.ReviewApproveConfig) actionConfig_,
                getParentForChildren(),
                isClean());
        actionConfig_ = null;
      }
      actionConfigCase_ = 7;
      onChanged();;
      return reviewApproveConfigBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewRequestChangesConfig, com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder, com.clarifai.grpc.api.ReviewRequestChangesConfigOrBuilder> reviewRequestChangesConfigBuilder_;
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     * @return Whether the reviewRequestChangesConfig field is set.
     */
    @java.lang.Override
    public boolean hasReviewRequestChangesConfig() {
      return actionConfigCase_ == 8;
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     * @return The reviewRequestChangesConfig.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewRequestChangesConfig getReviewRequestChangesConfig() {
      if (reviewRequestChangesConfigBuilder_ == null) {
        if (actionConfigCase_ == 8) {
          return (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
      } else {
        if (actionConfigCase_ == 8) {
          return reviewRequestChangesConfigBuilder_.getMessage();
        }
        return com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    public Builder setReviewRequestChangesConfig(com.clarifai.grpc.api.ReviewRequestChangesConfig value) {
      if (reviewRequestChangesConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionConfig_ = value;
        onChanged();
      } else {
        reviewRequestChangesConfigBuilder_.setMessage(value);
      }
      actionConfigCase_ = 8;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    public Builder setReviewRequestChangesConfig(
        com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder builderForValue) {
      if (reviewRequestChangesConfigBuilder_ == null) {
        actionConfig_ = builderForValue.build();
        onChanged();
      } else {
        reviewRequestChangesConfigBuilder_.setMessage(builderForValue.build());
      }
      actionConfigCase_ = 8;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    public Builder mergeReviewRequestChangesConfig(com.clarifai.grpc.api.ReviewRequestChangesConfig value) {
      if (reviewRequestChangesConfigBuilder_ == null) {
        if (actionConfigCase_ == 8 &&
            actionConfig_ != com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance()) {
          actionConfig_ = com.clarifai.grpc.api.ReviewRequestChangesConfig.newBuilder((com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_)
              .mergeFrom(value).buildPartial();
        } else {
          actionConfig_ = value;
        }
        onChanged();
      } else {
        if (actionConfigCase_ == 8) {
          reviewRequestChangesConfigBuilder_.mergeFrom(value);
        } else {
          reviewRequestChangesConfigBuilder_.setMessage(value);
        }
      }
      actionConfigCase_ = 8;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    public Builder clearReviewRequestChangesConfig() {
      if (reviewRequestChangesConfigBuilder_ == null) {
        if (actionConfigCase_ == 8) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
          onChanged();
        }
      } else {
        if (actionConfigCase_ == 8) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
        }
        reviewRequestChangesConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    public com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder getReviewRequestChangesConfigBuilder() {
      return getReviewRequestChangesConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewRequestChangesConfigOrBuilder getReviewRequestChangesConfigOrBuilder() {
      if ((actionConfigCase_ == 8) && (reviewRequestChangesConfigBuilder_ != null)) {
        return reviewRequestChangesConfigBuilder_.getMessageOrBuilder();
      } else {
        if (actionConfigCase_ == 8) {
          return (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewRequestChangesConfig review_request_changes_config = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewRequestChangesConfig, com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder, com.clarifai.grpc.api.ReviewRequestChangesConfigOrBuilder> 
        getReviewRequestChangesConfigFieldBuilder() {
      if (reviewRequestChangesConfigBuilder_ == null) {
        if (!(actionConfigCase_ == 8)) {
          actionConfig_ = com.clarifai.grpc.api.ReviewRequestChangesConfig.getDefaultInstance();
        }
        reviewRequestChangesConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.ReviewRequestChangesConfig, com.clarifai.grpc.api.ReviewRequestChangesConfig.Builder, com.clarifai.grpc.api.ReviewRequestChangesConfigOrBuilder>(
                (com.clarifai.grpc.api.ReviewRequestChangesConfig) actionConfig_,
                getParentForChildren(),
                isClean());
        actionConfig_ = null;
      }
      actionConfigCase_ = 8;
      onChanged();;
      return reviewRequestChangesConfigBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewRejectConfig, com.clarifai.grpc.api.ReviewRejectConfig.Builder, com.clarifai.grpc.api.ReviewRejectConfigOrBuilder> reviewRejectConfigBuilder_;
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     * @return Whether the reviewRejectConfig field is set.
     */
    @java.lang.Override
    public boolean hasReviewRejectConfig() {
      return actionConfigCase_ == 9;
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     * @return The reviewRejectConfig.
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewRejectConfig getReviewRejectConfig() {
      if (reviewRejectConfigBuilder_ == null) {
        if (actionConfigCase_ == 9) {
          return (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
      } else {
        if (actionConfigCase_ == 9) {
          return reviewRejectConfigBuilder_.getMessage();
        }
        return com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    public Builder setReviewRejectConfig(com.clarifai.grpc.api.ReviewRejectConfig value) {
      if (reviewRejectConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        actionConfig_ = value;
        onChanged();
      } else {
        reviewRejectConfigBuilder_.setMessage(value);
      }
      actionConfigCase_ = 9;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    public Builder setReviewRejectConfig(
        com.clarifai.grpc.api.ReviewRejectConfig.Builder builderForValue) {
      if (reviewRejectConfigBuilder_ == null) {
        actionConfig_ = builderForValue.build();
        onChanged();
      } else {
        reviewRejectConfigBuilder_.setMessage(builderForValue.build());
      }
      actionConfigCase_ = 9;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    public Builder mergeReviewRejectConfig(com.clarifai.grpc.api.ReviewRejectConfig value) {
      if (reviewRejectConfigBuilder_ == null) {
        if (actionConfigCase_ == 9 &&
            actionConfig_ != com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance()) {
          actionConfig_ = com.clarifai.grpc.api.ReviewRejectConfig.newBuilder((com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_)
              .mergeFrom(value).buildPartial();
        } else {
          actionConfig_ = value;
        }
        onChanged();
      } else {
        if (actionConfigCase_ == 9) {
          reviewRejectConfigBuilder_.mergeFrom(value);
        } else {
          reviewRejectConfigBuilder_.setMessage(value);
        }
      }
      actionConfigCase_ = 9;
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    public Builder clearReviewRejectConfig() {
      if (reviewRejectConfigBuilder_ == null) {
        if (actionConfigCase_ == 9) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
          onChanged();
        }
      } else {
        if (actionConfigCase_ == 9) {
          actionConfigCase_ = 0;
          actionConfig_ = null;
        }
        reviewRejectConfigBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    public com.clarifai.grpc.api.ReviewRejectConfig.Builder getReviewRejectConfigBuilder() {
      return getReviewRejectConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    @java.lang.Override
    public com.clarifai.grpc.api.ReviewRejectConfigOrBuilder getReviewRejectConfigOrBuilder() {
      if ((actionConfigCase_ == 9) && (reviewRejectConfigBuilder_ != null)) {
        return reviewRejectConfigBuilder_.getMessageOrBuilder();
      } else {
        if (actionConfigCase_ == 9) {
          return (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_;
        }
        return com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
      }
    }
    /**
     * <code>.clarifai.api.ReviewRejectConfig review_reject_config = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.ReviewRejectConfig, com.clarifai.grpc.api.ReviewRejectConfig.Builder, com.clarifai.grpc.api.ReviewRejectConfigOrBuilder> 
        getReviewRejectConfigFieldBuilder() {
      if (reviewRejectConfigBuilder_ == null) {
        if (!(actionConfigCase_ == 9)) {
          actionConfig_ = com.clarifai.grpc.api.ReviewRejectConfig.getDefaultInstance();
        }
        reviewRejectConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.ReviewRejectConfig, com.clarifai.grpc.api.ReviewRejectConfig.Builder, com.clarifai.grpc.api.ReviewRejectConfigOrBuilder>(
                (com.clarifai.grpc.api.ReviewRejectConfig) actionConfig_,
                getParentForChildren(),
                isClean());
        actionConfig_ = null;
      }
      actionConfigCase_ = 9;
      onChanged();;
      return reviewRejectConfigBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clarifai.api.PutTaskAssignmentsRequest)
  }

  // @@protoc_insertion_point(class_scope:clarifai.api.PutTaskAssignmentsRequest)
  private static final com.clarifai.grpc.api.PutTaskAssignmentsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clarifai.grpc.api.PutTaskAssignmentsRequest();
  }

  public static com.clarifai.grpc.api.PutTaskAssignmentsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PutTaskAssignmentsRequest>
      PARSER = new com.google.protobuf.AbstractParser<PutTaskAssignmentsRequest>() {
    @java.lang.Override
    public PutTaskAssignmentsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PutTaskAssignmentsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PutTaskAssignmentsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PutTaskAssignmentsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.clarifai.grpc.api.PutTaskAssignmentsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

