// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

/**
 * Protobuf type {@code clarifai.api.SinglePipelineVersionRunResponse}
 */
public final class SinglePipelineVersionRunResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clarifai.api.SinglePipelineVersionRunResponse)
    SinglePipelineVersionRunResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SinglePipelineVersionRunResponse.newBuilder() to construct.
  private SinglePipelineVersionRunResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SinglePipelineVersionRunResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SinglePipelineVersionRunResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SinglePipelineVersionRunResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.clarifai.grpc.api.status.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.clarifai.grpc.api.status.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.clarifai.grpc.api.PipelineVersionRun.Builder subBuilder = null;
            if (pipelineVersionRun_ != null) {
              subBuilder = pipelineVersionRun_.toBuilder();
            }
            pipelineVersionRun_ = input.readMessage(com.clarifai.grpc.api.PipelineVersionRun.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pipelineVersionRun_);
              pipelineVersionRun_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_SinglePipelineVersionRunResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clarifai.grpc.api.Service.internal_static_clarifai_api_SinglePipelineVersionRunResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clarifai.grpc.api.SinglePipelineVersionRunResponse.class, com.clarifai.grpc.api.SinglePipelineVersionRunResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private com.clarifai.grpc.api.status.Status status_;
  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.status.Status getStatus() {
    return status_ == null ? com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
  }
  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int PIPELINE_VERSION_RUN_FIELD_NUMBER = 2;
  private com.clarifai.grpc.api.PipelineVersionRun pipelineVersionRun_;
  /**
   * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
   * @return Whether the pipelineVersionRun field is set.
   */
  @java.lang.Override
  public boolean hasPipelineVersionRun() {
    return pipelineVersionRun_ != null;
  }
  /**
   * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
   * @return The pipelineVersionRun.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.PipelineVersionRun getPipelineVersionRun() {
    return pipelineVersionRun_ == null ? com.clarifai.grpc.api.PipelineVersionRun.getDefaultInstance() : pipelineVersionRun_;
  }
  /**
   * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.PipelineVersionRunOrBuilder getPipelineVersionRunOrBuilder() {
    return getPipelineVersionRun();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    if (pipelineVersionRun_ != null) {
      output.writeMessage(2, getPipelineVersionRun());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (pipelineVersionRun_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPipelineVersionRun());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.clarifai.grpc.api.SinglePipelineVersionRunResponse)) {
      return super.equals(obj);
    }
    com.clarifai.grpc.api.SinglePipelineVersionRunResponse other = (com.clarifai.grpc.api.SinglePipelineVersionRunResponse) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasPipelineVersionRun() != other.hasPipelineVersionRun()) return false;
    if (hasPipelineVersionRun()) {
      if (!getPipelineVersionRun()
          .equals(other.getPipelineVersionRun())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasPipelineVersionRun()) {
      hash = (37 * hash) + PIPELINE_VERSION_RUN_FIELD_NUMBER;
      hash = (53 * hash) + getPipelineVersionRun().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clarifai.grpc.api.SinglePipelineVersionRunResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clarifai.api.SinglePipelineVersionRunResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clarifai.api.SinglePipelineVersionRunResponse)
      com.clarifai.grpc.api.SinglePipelineVersionRunResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_SinglePipelineVersionRunResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_SinglePipelineVersionRunResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clarifai.grpc.api.SinglePipelineVersionRunResponse.class, com.clarifai.grpc.api.SinglePipelineVersionRunResponse.Builder.class);
    }

    // Construct using com.clarifai.grpc.api.SinglePipelineVersionRunResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (pipelineVersionRunBuilder_ == null) {
        pipelineVersionRun_ = null;
      } else {
        pipelineVersionRun_ = null;
        pipelineVersionRunBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clarifai.grpc.api.Service.internal_static_clarifai_api_SinglePipelineVersionRunResponse_descriptor;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.SinglePipelineVersionRunResponse getDefaultInstanceForType() {
      return com.clarifai.grpc.api.SinglePipelineVersionRunResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.clarifai.grpc.api.SinglePipelineVersionRunResponse build() {
      com.clarifai.grpc.api.SinglePipelineVersionRunResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.SinglePipelineVersionRunResponse buildPartial() {
      com.clarifai.grpc.api.SinglePipelineVersionRunResponse result = new com.clarifai.grpc.api.SinglePipelineVersionRunResponse(this);
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (pipelineVersionRunBuilder_ == null) {
        result.pipelineVersionRun_ = pipelineVersionRun_;
      } else {
        result.pipelineVersionRun_ = pipelineVersionRunBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clarifai.grpc.api.SinglePipelineVersionRunResponse) {
        return mergeFrom((com.clarifai.grpc.api.SinglePipelineVersionRunResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clarifai.grpc.api.SinglePipelineVersionRunResponse other) {
      if (other == com.clarifai.grpc.api.SinglePipelineVersionRunResponse.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasPipelineVersionRun()) {
        mergePipelineVersionRun(other.getPipelineVersionRun());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clarifai.grpc.api.SinglePipelineVersionRunResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clarifai.grpc.api.SinglePipelineVersionRunResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.clarifai.grpc.api.status.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder> statusBuilder_;
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     * @return The status.
     */
    public com.clarifai.grpc.api.status.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public Builder setStatus(com.clarifai.grpc.api.status.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public Builder setStatus(
        com.clarifai.grpc.api.status.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public Builder mergeStatus(com.clarifai.grpc.api.status.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.clarifai.grpc.api.status.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public com.clarifai.grpc.api.status.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    public com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.clarifai.api.status.Status status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.clarifai.grpc.api.PipelineVersionRun pipelineVersionRun_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.PipelineVersionRun, com.clarifai.grpc.api.PipelineVersionRun.Builder, com.clarifai.grpc.api.PipelineVersionRunOrBuilder> pipelineVersionRunBuilder_;
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     * @return Whether the pipelineVersionRun field is set.
     */
    public boolean hasPipelineVersionRun() {
      return pipelineVersionRunBuilder_ != null || pipelineVersionRun_ != null;
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     * @return The pipelineVersionRun.
     */
    public com.clarifai.grpc.api.PipelineVersionRun getPipelineVersionRun() {
      if (pipelineVersionRunBuilder_ == null) {
        return pipelineVersionRun_ == null ? com.clarifai.grpc.api.PipelineVersionRun.getDefaultInstance() : pipelineVersionRun_;
      } else {
        return pipelineVersionRunBuilder_.getMessage();
      }
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public Builder setPipelineVersionRun(com.clarifai.grpc.api.PipelineVersionRun value) {
      if (pipelineVersionRunBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pipelineVersionRun_ = value;
        onChanged();
      } else {
        pipelineVersionRunBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public Builder setPipelineVersionRun(
        com.clarifai.grpc.api.PipelineVersionRun.Builder builderForValue) {
      if (pipelineVersionRunBuilder_ == null) {
        pipelineVersionRun_ = builderForValue.build();
        onChanged();
      } else {
        pipelineVersionRunBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public Builder mergePipelineVersionRun(com.clarifai.grpc.api.PipelineVersionRun value) {
      if (pipelineVersionRunBuilder_ == null) {
        if (pipelineVersionRun_ != null) {
          pipelineVersionRun_ =
            com.clarifai.grpc.api.PipelineVersionRun.newBuilder(pipelineVersionRun_).mergeFrom(value).buildPartial();
        } else {
          pipelineVersionRun_ = value;
        }
        onChanged();
      } else {
        pipelineVersionRunBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public Builder clearPipelineVersionRun() {
      if (pipelineVersionRunBuilder_ == null) {
        pipelineVersionRun_ = null;
        onChanged();
      } else {
        pipelineVersionRun_ = null;
        pipelineVersionRunBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public com.clarifai.grpc.api.PipelineVersionRun.Builder getPipelineVersionRunBuilder() {
      
      onChanged();
      return getPipelineVersionRunFieldBuilder().getBuilder();
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    public com.clarifai.grpc.api.PipelineVersionRunOrBuilder getPipelineVersionRunOrBuilder() {
      if (pipelineVersionRunBuilder_ != null) {
        return pipelineVersionRunBuilder_.getMessageOrBuilder();
      } else {
        return pipelineVersionRun_ == null ?
            com.clarifai.grpc.api.PipelineVersionRun.getDefaultInstance() : pipelineVersionRun_;
      }
    }
    /**
     * <code>.clarifai.api.PipelineVersionRun pipeline_version_run = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.PipelineVersionRun, com.clarifai.grpc.api.PipelineVersionRun.Builder, com.clarifai.grpc.api.PipelineVersionRunOrBuilder> 
        getPipelineVersionRunFieldBuilder() {
      if (pipelineVersionRunBuilder_ == null) {
        pipelineVersionRunBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.PipelineVersionRun, com.clarifai.grpc.api.PipelineVersionRun.Builder, com.clarifai.grpc.api.PipelineVersionRunOrBuilder>(
                getPipelineVersionRun(),
                getParentForChildren(),
                isClean());
        pipelineVersionRun_ = null;
      }
      return pipelineVersionRunBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clarifai.api.SinglePipelineVersionRunResponse)
  }

  // @@protoc_insertion_point(class_scope:clarifai.api.SinglePipelineVersionRunResponse)
  private static final com.clarifai.grpc.api.SinglePipelineVersionRunResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clarifai.grpc.api.SinglePipelineVersionRunResponse();
  }

  public static com.clarifai.grpc.api.SinglePipelineVersionRunResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SinglePipelineVersionRunResponse>
      PARSER = new com.google.protobuf.AbstractParser<SinglePipelineVersionRunResponse>() {
    @java.lang.Override
    public SinglePipelineVersionRunResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SinglePipelineVersionRunResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SinglePipelineVersionRunResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SinglePipelineVersionRunResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.clarifai.grpc.api.SinglePipelineVersionRunResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

