// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/service.proto

package com.clarifai.grpc.api;

public interface SingleModelVersionExportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.SingleModelVersionExportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   * @return The status.
   */
  com.clarifai.grpc.api.status.Status getStatus();
  /**
   * <code>.clarifai.api.status.Status status = 1;</code>
   */
  com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.clarifai.api.ModelVersionExport export = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
   * @return Whether the export field is set.
   */
  boolean hasExport();
  /**
   * <code>.clarifai.api.ModelVersionExport export = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
   * @return The export.
   */
  com.clarifai.grpc.api.ModelVersionExport getExport();
  /**
   * <code>.clarifai.api.ModelVersionExport export = 2 [(.clarifai.api.utils.cl_show_if_empty) = true];</code>
   */
  com.clarifai.grpc.api.ModelVersionExportOrBuilder getExportOrBuilder();
}
