// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface StatValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.StatValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The time of the event. Defaults to now().
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <pre>
   * The time of the event. Defaults to now().
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   * @return The time.
   */
  com.google.protobuf.Timestamp getTime();
  /**
   * <pre>
   * The time of the event. Defaults to now().
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeOrBuilder();

  /**
   * <pre>
   * A value for the metric you're recording.
   * </pre>
   *
   * <code>float value = 2;</code>
   * @return The value.
   */
  float getValue();

  /**
   * <pre>
   * List of tags to attach to this stat. Each should contain one colon so that the first part will
   * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
   * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
   * values in the StatValueAggregateQuery.
   * </pre>
   *
   * <code>repeated string tags = 3;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * List of tags to attach to this stat. Each should contain one colon so that the first part will
   * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
   * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
   * values in the StatValueAggregateQuery.
   * </pre>
   *
   * <code>repeated string tags = 3;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * List of tags to attach to this stat. Each should contain one colon so that the first part will
   * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
   * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
   * values in the StatValueAggregateQuery.
   * </pre>
   *
   * <code>repeated string tags = 3;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * List of tags to attach to this stat. Each should contain one colon so that the first part will
   * be used as a tag group while the second being the tag itself. For example: ["task_id:a",
   * "worker_id:1"]. These tag groups like "task_id" or "worker_id" are important for aggregating
   * values in the StatValueAggregateQuery.
   * </pre>
   *
   * <code>repeated string tags = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);
}
