// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

public interface TaskReviewMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clarifai.api.TaskReviewMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Estimated number of reviewed inputs.
   * </pre>
   *
   * <code>uint64 inputs_count_estimated = 1;</code>
   * @return The inputsCountEstimated.
   */
  long getInputsCountEstimated();

  /**
   * <pre>
   * Estimated percent of inputs that were reviewed. Calculated as count of reviewed inputs / total task inputs
   * This is a value between 0 and 100, where 0 = 0% and 100 = 100%.
   * </pre>
   *
   * <code>uint32 inputs_percent_estimated = 2;</code>
   * @return The inputsPercentEstimated.
   */
  int getInputsPercentEstimated();
}
