// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/resources.proto

package com.clarifai.grpc.api;

/**
 * Protobuf type {@code clarifai.api.WorkflowVersionEvaluation}
 */
public final class WorkflowVersionEvaluation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clarifai.api.WorkflowVersionEvaluation)
    WorkflowVersionEvaluationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkflowVersionEvaluation.newBuilder() to construct.
  private WorkflowVersionEvaluation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkflowVersionEvaluation() {
    id_ = "";
    workflowId_ = "";
    workflowVersionId_ = "";
    groundTruthDatasetId_ = "";
    groundTruthDatasetVersionId_ = "";
    predictionsDatasetId_ = "";
    predictionsDatasetVersionId_ = "";
    evaluationTemplateId_ = "";
    targetNodeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkflowVersionEvaluation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkflowVersionEvaluation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            workflowId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            workflowVersionId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            groundTruthDatasetId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            groundTruthDatasetVersionId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            predictionsDatasetId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            predictionsDatasetVersionId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            evaluationTemplateId_ = s;
            break;
          }
          case 74: {
            com.clarifai.grpc.api.WorkflowEvaluationResult.Builder subBuilder = null;
            if (workflowEvaluationResult_ != null) {
              subBuilder = workflowEvaluationResult_.toBuilder();
            }
            workflowEvaluationResult_ = input.readMessage(com.clarifai.grpc.api.WorkflowEvaluationResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(workflowEvaluationResult_);
              workflowEvaluationResult_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.clarifai.grpc.api.status.Status.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.clarifai.grpc.api.status.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (modifiedAt_ != null) {
              subBuilder = modifiedAt_.toBuilder();
            }
            modifiedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(modifiedAt_);
              modifiedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            targetNodeId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.clarifai.grpc.api.Resources.internal_static_clarifai_api_WorkflowVersionEvaluation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.clarifai.grpc.api.Resources.internal_static_clarifai_api_WorkflowVersionEvaluation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.clarifai.grpc.api.WorkflowVersionEvaluation.class, com.clarifai.grpc.api.WorkflowVersionEvaluation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Customer-Facing / External ID of the workflow version evaluation.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Customer-Facing / External ID of the workflow version evaluation.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKFLOW_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object workflowId_;
  /**
   * <pre>
   * The ID of the workflow that is used for evaluation.
   * </pre>
   *
   * <code>string workflow_id = 2;</code>
   * @return The workflowId.
   */
  @java.lang.Override
  public java.lang.String getWorkflowId() {
    java.lang.Object ref = workflowId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workflowId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the workflow that is used for evaluation.
   * </pre>
   *
   * <code>string workflow_id = 2;</code>
   * @return The bytes for workflowId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkflowIdBytes() {
    java.lang.Object ref = workflowId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workflowId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKFLOW_VERSION_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object workflowVersionId_;
  /**
   * <pre>
   * The version of the workflow that is used for evaluation.
   * </pre>
   *
   * <code>string workflow_version_id = 3;</code>
   * @return The workflowVersionId.
   */
  @java.lang.Override
  public java.lang.String getWorkflowVersionId() {
    java.lang.Object ref = workflowVersionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      workflowVersionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version of the workflow that is used for evaluation.
   * </pre>
   *
   * <code>string workflow_version_id = 3;</code>
   * @return The bytes for workflowVersionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkflowVersionIdBytes() {
    java.lang.Object ref = workflowVersionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      workflowVersionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUND_TRUTH_DATASET_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object groundTruthDatasetId_;
  /**
   * <pre>
   * The ID of the ground-truth dataset that is used for evaluation.
   * </pre>
   *
   * <code>string ground_truth_dataset_id = 4;</code>
   * @return The groundTruthDatasetId.
   */
  @java.lang.Override
  public java.lang.String getGroundTruthDatasetId() {
    java.lang.Object ref = groundTruthDatasetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groundTruthDatasetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the ground-truth dataset that is used for evaluation.
   * </pre>
   *
   * <code>string ground_truth_dataset_id = 4;</code>
   * @return The bytes for groundTruthDatasetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroundTruthDatasetIdBytes() {
    java.lang.Object ref = groundTruthDatasetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groundTruthDatasetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUND_TRUTH_DATASET_VERSION_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object groundTruthDatasetVersionId_;
  /**
   * <pre>
   * The version ID of the ground-truth dataset that is used for evaluation.
   * </pre>
   *
   * <code>string ground_truth_dataset_version_id = 5;</code>
   * @return The groundTruthDatasetVersionId.
   */
  @java.lang.Override
  public java.lang.String getGroundTruthDatasetVersionId() {
    java.lang.Object ref = groundTruthDatasetVersionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groundTruthDatasetVersionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version ID of the ground-truth dataset that is used for evaluation.
   * </pre>
   *
   * <code>string ground_truth_dataset_version_id = 5;</code>
   * @return The bytes for groundTruthDatasetVersionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroundTruthDatasetVersionIdBytes() {
    java.lang.Object ref = groundTruthDatasetVersionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groundTruthDatasetVersionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREDICTIONS_DATASET_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object predictionsDatasetId_;
  /**
   * <pre>
   * The ID of the prediction dataset that is used for evaluation.
   * </pre>
   *
   * <code>string predictions_dataset_id = 6;</code>
   * @return The predictionsDatasetId.
   */
  @java.lang.Override
  public java.lang.String getPredictionsDatasetId() {
    java.lang.Object ref = predictionsDatasetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      predictionsDatasetId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the prediction dataset that is used for evaluation.
   * </pre>
   *
   * <code>string predictions_dataset_id = 6;</code>
   * @return The bytes for predictionsDatasetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPredictionsDatasetIdBytes() {
    java.lang.Object ref = predictionsDatasetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      predictionsDatasetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREDICTIONS_DATASET_VERSION_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object predictionsDatasetVersionId_;
  /**
   * <pre>
   * The version ID of the prediction dataset that is used for evaluation.
   * </pre>
   *
   * <code>string predictions_dataset_version_id = 7;</code>
   * @return The predictionsDatasetVersionId.
   */
  @java.lang.Override
  public java.lang.String getPredictionsDatasetVersionId() {
    java.lang.Object ref = predictionsDatasetVersionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      predictionsDatasetVersionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version ID of the prediction dataset that is used for evaluation.
   * </pre>
   *
   * <code>string predictions_dataset_version_id = 7;</code>
   * @return The bytes for predictionsDatasetVersionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPredictionsDatasetVersionIdBytes() {
    java.lang.Object ref = predictionsDatasetVersionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      predictionsDatasetVersionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVALUATION_TEMPLATE_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object evaluationTemplateId_;
  /**
   * <pre>
   * Evaluation Template ID
   * </pre>
   *
   * <code>string evaluation_template_id = 8;</code>
   * @return The evaluationTemplateId.
   */
  @java.lang.Override
  public java.lang.String getEvaluationTemplateId() {
    java.lang.Object ref = evaluationTemplateId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      evaluationTemplateId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Evaluation Template ID
   * </pre>
   *
   * <code>string evaluation_template_id = 8;</code>
   * @return The bytes for evaluationTemplateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEvaluationTemplateIdBytes() {
    java.lang.Object ref = evaluationTemplateId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      evaluationTemplateId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORKFLOW_EVALUATION_RESULT_FIELD_NUMBER = 9;
  private com.clarifai.grpc.api.WorkflowEvaluationResult workflowEvaluationResult_;
  /**
   * <pre>
   * The evaluation results
   * </pre>
   *
   * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
   * @return Whether the workflowEvaluationResult field is set.
   */
  @java.lang.Override
  public boolean hasWorkflowEvaluationResult() {
    return workflowEvaluationResult_ != null;
  }
  /**
   * <pre>
   * The evaluation results
   * </pre>
   *
   * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
   * @return The workflowEvaluationResult.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.WorkflowEvaluationResult getWorkflowEvaluationResult() {
    return workflowEvaluationResult_ == null ? com.clarifai.grpc.api.WorkflowEvaluationResult.getDefaultInstance() : workflowEvaluationResult_;
  }
  /**
   * <pre>
   * The evaluation results
   * </pre>
   *
   * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.WorkflowEvaluationResultOrBuilder getWorkflowEvaluationResultOrBuilder() {
    return getWorkflowEvaluationResult();
  }

  public static final int STATUS_FIELD_NUMBER = 10;
  private com.clarifai.grpc.api.status.Status status_;
  /**
   * <pre>
   * Status of the evaluation
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 10;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <pre>
   * Status of the evaluation
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 10;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.clarifai.grpc.api.status.Status getStatus() {
    return status_ == null ? com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
  }
  /**
   * <pre>
   * Status of the evaluation
   * </pre>
   *
   * <code>.clarifai.api.status.Status status = 10;</code>
   */
  @java.lang.Override
  public com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int CREATED_AT_FIELD_NUMBER = 11;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <pre>
   * When the workflow version evaluation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 11;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <pre>
   * When the workflow version evaluation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 11;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <pre>
   * When the workflow version evaluation was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 11;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int MODIFIED_AT_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp modifiedAt_;
  /**
   * <pre>
   * When the workflow version evaluation was modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 12;</code>
   * @return Whether the modifiedAt field is set.
   */
  @java.lang.Override
  public boolean hasModifiedAt() {
    return modifiedAt_ != null;
  }
  /**
   * <pre>
   * When the workflow version evaluation was modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 12;</code>
   * @return The modifiedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getModifiedAt() {
    return modifiedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifiedAt_;
  }
  /**
   * <pre>
   * When the workflow version evaluation was modified.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp modified_at = 12;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder() {
    return getModifiedAt();
  }

  public static final int TARGET_NODE_ID_FIELD_NUMBER = 13;
  private volatile java.lang.Object targetNodeId_;
  /**
   * <pre>
   * The ID of the node that is being evaluated.
   * </pre>
   *
   * <code>string target_node_id = 13;</code>
   * @return The targetNodeId.
   */
  @java.lang.Override
  public java.lang.String getTargetNodeId() {
    java.lang.Object ref = targetNodeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetNodeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the node that is being evaluated.
   * </pre>
   *
   * <code>string target_node_id = 13;</code>
   * @return The bytes for targetNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetNodeIdBytes() {
    java.lang.Object ref = targetNodeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetNodeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workflowId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, workflowId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workflowVersionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, workflowVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groundTruthDatasetId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, groundTruthDatasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groundTruthDatasetVersionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, groundTruthDatasetVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predictionsDatasetId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, predictionsDatasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predictionsDatasetVersionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, predictionsDatasetVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(evaluationTemplateId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, evaluationTemplateId_);
    }
    if (workflowEvaluationResult_ != null) {
      output.writeMessage(9, getWorkflowEvaluationResult());
    }
    if (status_ != null) {
      output.writeMessage(10, getStatus());
    }
    if (createdAt_ != null) {
      output.writeMessage(11, getCreatedAt());
    }
    if (modifiedAt_ != null) {
      output.writeMessage(12, getModifiedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetNodeId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, targetNodeId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workflowId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, workflowId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(workflowVersionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, workflowVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groundTruthDatasetId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, groundTruthDatasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(groundTruthDatasetVersionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, groundTruthDatasetVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predictionsDatasetId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, predictionsDatasetId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predictionsDatasetVersionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, predictionsDatasetVersionId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(evaluationTemplateId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, evaluationTemplateId_);
    }
    if (workflowEvaluationResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getWorkflowEvaluationResult());
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getStatus());
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCreatedAt());
    }
    if (modifiedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getModifiedAt());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetNodeId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, targetNodeId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.clarifai.grpc.api.WorkflowVersionEvaluation)) {
      return super.equals(obj);
    }
    com.clarifai.grpc.api.WorkflowVersionEvaluation other = (com.clarifai.grpc.api.WorkflowVersionEvaluation) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getWorkflowId()
        .equals(other.getWorkflowId())) return false;
    if (!getWorkflowVersionId()
        .equals(other.getWorkflowVersionId())) return false;
    if (!getGroundTruthDatasetId()
        .equals(other.getGroundTruthDatasetId())) return false;
    if (!getGroundTruthDatasetVersionId()
        .equals(other.getGroundTruthDatasetVersionId())) return false;
    if (!getPredictionsDatasetId()
        .equals(other.getPredictionsDatasetId())) return false;
    if (!getPredictionsDatasetVersionId()
        .equals(other.getPredictionsDatasetVersionId())) return false;
    if (!getEvaluationTemplateId()
        .equals(other.getEvaluationTemplateId())) return false;
    if (hasWorkflowEvaluationResult() != other.hasWorkflowEvaluationResult()) return false;
    if (hasWorkflowEvaluationResult()) {
      if (!getWorkflowEvaluationResult()
          .equals(other.getWorkflowEvaluationResult())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasModifiedAt() != other.hasModifiedAt()) return false;
    if (hasModifiedAt()) {
      if (!getModifiedAt()
          .equals(other.getModifiedAt())) return false;
    }
    if (!getTargetNodeId()
        .equals(other.getTargetNodeId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + WORKFLOW_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkflowId().hashCode();
    hash = (37 * hash) + WORKFLOW_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkflowVersionId().hashCode();
    hash = (37 * hash) + GROUND_TRUTH_DATASET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroundTruthDatasetId().hashCode();
    hash = (37 * hash) + GROUND_TRUTH_DATASET_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGroundTruthDatasetVersionId().hashCode();
    hash = (37 * hash) + PREDICTIONS_DATASET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPredictionsDatasetId().hashCode();
    hash = (37 * hash) + PREDICTIONS_DATASET_VERSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPredictionsDatasetVersionId().hashCode();
    hash = (37 * hash) + EVALUATION_TEMPLATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEvaluationTemplateId().hashCode();
    if (hasWorkflowEvaluationResult()) {
      hash = (37 * hash) + WORKFLOW_EVALUATION_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowEvaluationResult().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasModifiedAt()) {
      hash = (37 * hash) + MODIFIED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getModifiedAt().hashCode();
    }
    hash = (37 * hash) + TARGET_NODE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetNodeId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.clarifai.grpc.api.WorkflowVersionEvaluation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.clarifai.grpc.api.WorkflowVersionEvaluation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clarifai.api.WorkflowVersionEvaluation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clarifai.api.WorkflowVersionEvaluation)
      com.clarifai.grpc.api.WorkflowVersionEvaluationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.clarifai.grpc.api.Resources.internal_static_clarifai_api_WorkflowVersionEvaluation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.clarifai.grpc.api.Resources.internal_static_clarifai_api_WorkflowVersionEvaluation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.clarifai.grpc.api.WorkflowVersionEvaluation.class, com.clarifai.grpc.api.WorkflowVersionEvaluation.Builder.class);
    }

    // Construct using com.clarifai.grpc.api.WorkflowVersionEvaluation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      workflowId_ = "";

      workflowVersionId_ = "";

      groundTruthDatasetId_ = "";

      groundTruthDatasetVersionId_ = "";

      predictionsDatasetId_ = "";

      predictionsDatasetVersionId_ = "";

      evaluationTemplateId_ = "";

      if (workflowEvaluationResultBuilder_ == null) {
        workflowEvaluationResult_ = null;
      } else {
        workflowEvaluationResult_ = null;
        workflowEvaluationResultBuilder_ = null;
      }
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      if (modifiedAtBuilder_ == null) {
        modifiedAt_ = null;
      } else {
        modifiedAt_ = null;
        modifiedAtBuilder_ = null;
      }
      targetNodeId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.clarifai.grpc.api.Resources.internal_static_clarifai_api_WorkflowVersionEvaluation_descriptor;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.WorkflowVersionEvaluation getDefaultInstanceForType() {
      return com.clarifai.grpc.api.WorkflowVersionEvaluation.getDefaultInstance();
    }

    @java.lang.Override
    public com.clarifai.grpc.api.WorkflowVersionEvaluation build() {
      com.clarifai.grpc.api.WorkflowVersionEvaluation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.clarifai.grpc.api.WorkflowVersionEvaluation buildPartial() {
      com.clarifai.grpc.api.WorkflowVersionEvaluation result = new com.clarifai.grpc.api.WorkflowVersionEvaluation(this);
      result.id_ = id_;
      result.workflowId_ = workflowId_;
      result.workflowVersionId_ = workflowVersionId_;
      result.groundTruthDatasetId_ = groundTruthDatasetId_;
      result.groundTruthDatasetVersionId_ = groundTruthDatasetVersionId_;
      result.predictionsDatasetId_ = predictionsDatasetId_;
      result.predictionsDatasetVersionId_ = predictionsDatasetVersionId_;
      result.evaluationTemplateId_ = evaluationTemplateId_;
      if (workflowEvaluationResultBuilder_ == null) {
        result.workflowEvaluationResult_ = workflowEvaluationResult_;
      } else {
        result.workflowEvaluationResult_ = workflowEvaluationResultBuilder_.build();
      }
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      if (modifiedAtBuilder_ == null) {
        result.modifiedAt_ = modifiedAt_;
      } else {
        result.modifiedAt_ = modifiedAtBuilder_.build();
      }
      result.targetNodeId_ = targetNodeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.clarifai.grpc.api.WorkflowVersionEvaluation) {
        return mergeFrom((com.clarifai.grpc.api.WorkflowVersionEvaluation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.clarifai.grpc.api.WorkflowVersionEvaluation other) {
      if (other == com.clarifai.grpc.api.WorkflowVersionEvaluation.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getWorkflowId().isEmpty()) {
        workflowId_ = other.workflowId_;
        onChanged();
      }
      if (!other.getWorkflowVersionId().isEmpty()) {
        workflowVersionId_ = other.workflowVersionId_;
        onChanged();
      }
      if (!other.getGroundTruthDatasetId().isEmpty()) {
        groundTruthDatasetId_ = other.groundTruthDatasetId_;
        onChanged();
      }
      if (!other.getGroundTruthDatasetVersionId().isEmpty()) {
        groundTruthDatasetVersionId_ = other.groundTruthDatasetVersionId_;
        onChanged();
      }
      if (!other.getPredictionsDatasetId().isEmpty()) {
        predictionsDatasetId_ = other.predictionsDatasetId_;
        onChanged();
      }
      if (!other.getPredictionsDatasetVersionId().isEmpty()) {
        predictionsDatasetVersionId_ = other.predictionsDatasetVersionId_;
        onChanged();
      }
      if (!other.getEvaluationTemplateId().isEmpty()) {
        evaluationTemplateId_ = other.evaluationTemplateId_;
        onChanged();
      }
      if (other.hasWorkflowEvaluationResult()) {
        mergeWorkflowEvaluationResult(other.getWorkflowEvaluationResult());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasModifiedAt()) {
        mergeModifiedAt(other.getModifiedAt());
      }
      if (!other.getTargetNodeId().isEmpty()) {
        targetNodeId_ = other.targetNodeId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.clarifai.grpc.api.WorkflowVersionEvaluation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.clarifai.grpc.api.WorkflowVersionEvaluation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Customer-Facing / External ID of the workflow version evaluation.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Customer-Facing / External ID of the workflow version evaluation.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Customer-Facing / External ID of the workflow version evaluation.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Customer-Facing / External ID of the workflow version evaluation.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Customer-Facing / External ID of the workflow version evaluation.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object workflowId_ = "";
    /**
     * <pre>
     * The ID of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_id = 2;</code>
     * @return The workflowId.
     */
    public java.lang.String getWorkflowId() {
      java.lang.Object ref = workflowId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_id = 2;</code>
     * @return The bytes for workflowId.
     */
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_id = 2;</code>
     * @param value The workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workflowId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkflowId() {
      
      workflowId_ = getDefaultInstance().getWorkflowId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_id = 2;</code>
     * @param value The bytes for workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workflowId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object workflowVersionId_ = "";
    /**
     * <pre>
     * The version of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_version_id = 3;</code>
     * @return The workflowVersionId.
     */
    public java.lang.String getWorkflowVersionId() {
      java.lang.Object ref = workflowVersionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowVersionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_version_id = 3;</code>
     * @return The bytes for workflowVersionId.
     */
    public com.google.protobuf.ByteString
        getWorkflowVersionIdBytes() {
      java.lang.Object ref = workflowVersionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowVersionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_version_id = 3;</code>
     * @param value The workflowVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowVersionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      workflowVersionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_version_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkflowVersionId() {
      
      workflowVersionId_ = getDefaultInstance().getWorkflowVersionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of the workflow that is used for evaluation.
     * </pre>
     *
     * <code>string workflow_version_id = 3;</code>
     * @param value The bytes for workflowVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowVersionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      workflowVersionId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object groundTruthDatasetId_ = "";
    /**
     * <pre>
     * The ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_id = 4;</code>
     * @return The groundTruthDatasetId.
     */
    public java.lang.String getGroundTruthDatasetId() {
      java.lang.Object ref = groundTruthDatasetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groundTruthDatasetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_id = 4;</code>
     * @return The bytes for groundTruthDatasetId.
     */
    public com.google.protobuf.ByteString
        getGroundTruthDatasetIdBytes() {
      java.lang.Object ref = groundTruthDatasetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groundTruthDatasetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_id = 4;</code>
     * @param value The groundTruthDatasetId to set.
     * @return This builder for chaining.
     */
    public Builder setGroundTruthDatasetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groundTruthDatasetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroundTruthDatasetId() {
      
      groundTruthDatasetId_ = getDefaultInstance().getGroundTruthDatasetId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_id = 4;</code>
     * @param value The bytes for groundTruthDatasetId to set.
     * @return This builder for chaining.
     */
    public Builder setGroundTruthDatasetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groundTruthDatasetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object groundTruthDatasetVersionId_ = "";
    /**
     * <pre>
     * The version ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_version_id = 5;</code>
     * @return The groundTruthDatasetVersionId.
     */
    public java.lang.String getGroundTruthDatasetVersionId() {
      java.lang.Object ref = groundTruthDatasetVersionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groundTruthDatasetVersionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_version_id = 5;</code>
     * @return The bytes for groundTruthDatasetVersionId.
     */
    public com.google.protobuf.ByteString
        getGroundTruthDatasetVersionIdBytes() {
      java.lang.Object ref = groundTruthDatasetVersionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groundTruthDatasetVersionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_version_id = 5;</code>
     * @param value The groundTruthDatasetVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setGroundTruthDatasetVersionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groundTruthDatasetVersionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_version_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroundTruthDatasetVersionId() {
      
      groundTruthDatasetVersionId_ = getDefaultInstance().getGroundTruthDatasetVersionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version ID of the ground-truth dataset that is used for evaluation.
     * </pre>
     *
     * <code>string ground_truth_dataset_version_id = 5;</code>
     * @param value The bytes for groundTruthDatasetVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setGroundTruthDatasetVersionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groundTruthDatasetVersionId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object predictionsDatasetId_ = "";
    /**
     * <pre>
     * The ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_id = 6;</code>
     * @return The predictionsDatasetId.
     */
    public java.lang.String getPredictionsDatasetId() {
      java.lang.Object ref = predictionsDatasetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        predictionsDatasetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_id = 6;</code>
     * @return The bytes for predictionsDatasetId.
     */
    public com.google.protobuf.ByteString
        getPredictionsDatasetIdBytes() {
      java.lang.Object ref = predictionsDatasetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        predictionsDatasetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_id = 6;</code>
     * @param value The predictionsDatasetId to set.
     * @return This builder for chaining.
     */
    public Builder setPredictionsDatasetId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      predictionsDatasetId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPredictionsDatasetId() {
      
      predictionsDatasetId_ = getDefaultInstance().getPredictionsDatasetId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_id = 6;</code>
     * @param value The bytes for predictionsDatasetId to set.
     * @return This builder for chaining.
     */
    public Builder setPredictionsDatasetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      predictionsDatasetId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object predictionsDatasetVersionId_ = "";
    /**
     * <pre>
     * The version ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_version_id = 7;</code>
     * @return The predictionsDatasetVersionId.
     */
    public java.lang.String getPredictionsDatasetVersionId() {
      java.lang.Object ref = predictionsDatasetVersionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        predictionsDatasetVersionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_version_id = 7;</code>
     * @return The bytes for predictionsDatasetVersionId.
     */
    public com.google.protobuf.ByteString
        getPredictionsDatasetVersionIdBytes() {
      java.lang.Object ref = predictionsDatasetVersionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        predictionsDatasetVersionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_version_id = 7;</code>
     * @param value The predictionsDatasetVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setPredictionsDatasetVersionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      predictionsDatasetVersionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_version_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPredictionsDatasetVersionId() {
      
      predictionsDatasetVersionId_ = getDefaultInstance().getPredictionsDatasetVersionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version ID of the prediction dataset that is used for evaluation.
     * </pre>
     *
     * <code>string predictions_dataset_version_id = 7;</code>
     * @param value The bytes for predictionsDatasetVersionId to set.
     * @return This builder for chaining.
     */
    public Builder setPredictionsDatasetVersionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      predictionsDatasetVersionId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object evaluationTemplateId_ = "";
    /**
     * <pre>
     * Evaluation Template ID
     * </pre>
     *
     * <code>string evaluation_template_id = 8;</code>
     * @return The evaluationTemplateId.
     */
    public java.lang.String getEvaluationTemplateId() {
      java.lang.Object ref = evaluationTemplateId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        evaluationTemplateId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Evaluation Template ID
     * </pre>
     *
     * <code>string evaluation_template_id = 8;</code>
     * @return The bytes for evaluationTemplateId.
     */
    public com.google.protobuf.ByteString
        getEvaluationTemplateIdBytes() {
      java.lang.Object ref = evaluationTemplateId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        evaluationTemplateId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Evaluation Template ID
     * </pre>
     *
     * <code>string evaluation_template_id = 8;</code>
     * @param value The evaluationTemplateId to set.
     * @return This builder for chaining.
     */
    public Builder setEvaluationTemplateId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      evaluationTemplateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Evaluation Template ID
     * </pre>
     *
     * <code>string evaluation_template_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvaluationTemplateId() {
      
      evaluationTemplateId_ = getDefaultInstance().getEvaluationTemplateId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Evaluation Template ID
     * </pre>
     *
     * <code>string evaluation_template_id = 8;</code>
     * @param value The bytes for evaluationTemplateId to set.
     * @return This builder for chaining.
     */
    public Builder setEvaluationTemplateIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      evaluationTemplateId_ = value;
      onChanged();
      return this;
    }

    private com.clarifai.grpc.api.WorkflowEvaluationResult workflowEvaluationResult_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.WorkflowEvaluationResult, com.clarifai.grpc.api.WorkflowEvaluationResult.Builder, com.clarifai.grpc.api.WorkflowEvaluationResultOrBuilder> workflowEvaluationResultBuilder_;
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     * @return Whether the workflowEvaluationResult field is set.
     */
    public boolean hasWorkflowEvaluationResult() {
      return workflowEvaluationResultBuilder_ != null || workflowEvaluationResult_ != null;
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     * @return The workflowEvaluationResult.
     */
    public com.clarifai.grpc.api.WorkflowEvaluationResult getWorkflowEvaluationResult() {
      if (workflowEvaluationResultBuilder_ == null) {
        return workflowEvaluationResult_ == null ? com.clarifai.grpc.api.WorkflowEvaluationResult.getDefaultInstance() : workflowEvaluationResult_;
      } else {
        return workflowEvaluationResultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public Builder setWorkflowEvaluationResult(com.clarifai.grpc.api.WorkflowEvaluationResult value) {
      if (workflowEvaluationResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        workflowEvaluationResult_ = value;
        onChanged();
      } else {
        workflowEvaluationResultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public Builder setWorkflowEvaluationResult(
        com.clarifai.grpc.api.WorkflowEvaluationResult.Builder builderForValue) {
      if (workflowEvaluationResultBuilder_ == null) {
        workflowEvaluationResult_ = builderForValue.build();
        onChanged();
      } else {
        workflowEvaluationResultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public Builder mergeWorkflowEvaluationResult(com.clarifai.grpc.api.WorkflowEvaluationResult value) {
      if (workflowEvaluationResultBuilder_ == null) {
        if (workflowEvaluationResult_ != null) {
          workflowEvaluationResult_ =
            com.clarifai.grpc.api.WorkflowEvaluationResult.newBuilder(workflowEvaluationResult_).mergeFrom(value).buildPartial();
        } else {
          workflowEvaluationResult_ = value;
        }
        onChanged();
      } else {
        workflowEvaluationResultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public Builder clearWorkflowEvaluationResult() {
      if (workflowEvaluationResultBuilder_ == null) {
        workflowEvaluationResult_ = null;
        onChanged();
      } else {
        workflowEvaluationResult_ = null;
        workflowEvaluationResultBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public com.clarifai.grpc.api.WorkflowEvaluationResult.Builder getWorkflowEvaluationResultBuilder() {
      
      onChanged();
      return getWorkflowEvaluationResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    public com.clarifai.grpc.api.WorkflowEvaluationResultOrBuilder getWorkflowEvaluationResultOrBuilder() {
      if (workflowEvaluationResultBuilder_ != null) {
        return workflowEvaluationResultBuilder_.getMessageOrBuilder();
      } else {
        return workflowEvaluationResult_ == null ?
            com.clarifai.grpc.api.WorkflowEvaluationResult.getDefaultInstance() : workflowEvaluationResult_;
      }
    }
    /**
     * <pre>
     * The evaluation results
     * </pre>
     *
     * <code>.clarifai.api.WorkflowEvaluationResult workflow_evaluation_result = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.WorkflowEvaluationResult, com.clarifai.grpc.api.WorkflowEvaluationResult.Builder, com.clarifai.grpc.api.WorkflowEvaluationResultOrBuilder> 
        getWorkflowEvaluationResultFieldBuilder() {
      if (workflowEvaluationResultBuilder_ == null) {
        workflowEvaluationResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.WorkflowEvaluationResult, com.clarifai.grpc.api.WorkflowEvaluationResult.Builder, com.clarifai.grpc.api.WorkflowEvaluationResultOrBuilder>(
                getWorkflowEvaluationResult(),
                getParentForChildren(),
                isClean());
        workflowEvaluationResult_ = null;
      }
      return workflowEvaluationResultBuilder_;
    }

    private com.clarifai.grpc.api.status.Status status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder> statusBuilder_;
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     * @return The status.
     */
    public com.clarifai.grpc.api.status.Status getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public Builder setStatus(com.clarifai.grpc.api.status.Status value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public Builder setStatus(
        com.clarifai.grpc.api.status.Status.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public Builder mergeStatus(com.clarifai.grpc.api.status.Status value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.clarifai.grpc.api.status.Status.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public com.clarifai.grpc.api.status.Status.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    public com.clarifai.grpc.api.status.StatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.clarifai.grpc.api.status.Status.getDefaultInstance() : status_;
      }
    }
    /**
     * <pre>
     * Status of the evaluation
     * </pre>
     *
     * <code>.clarifai.api.status.Status status = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.clarifai.grpc.api.status.Status, com.clarifai.grpc.api.status.Status.Builder, com.clarifai.grpc.api.status.StatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <pre>
     * When the workflow version evaluation was created.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp created_at = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp modifiedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedAtBuilder_;
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     * @return Whether the modifiedAt field is set.
     */
    public boolean hasModifiedAt() {
      return modifiedAtBuilder_ != null || modifiedAt_ != null;
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     * @return The modifiedAt.
     */
    public com.google.protobuf.Timestamp getModifiedAt() {
      if (modifiedAtBuilder_ == null) {
        return modifiedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifiedAt_;
      } else {
        return modifiedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public Builder setModifiedAt(com.google.protobuf.Timestamp value) {
      if (modifiedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        modifiedAt_ = value;
        onChanged();
      } else {
        modifiedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public Builder setModifiedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (modifiedAtBuilder_ == null) {
        modifiedAt_ = builderForValue.build();
        onChanged();
      } else {
        modifiedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public Builder mergeModifiedAt(com.google.protobuf.Timestamp value) {
      if (modifiedAtBuilder_ == null) {
        if (modifiedAt_ != null) {
          modifiedAt_ =
            com.google.protobuf.Timestamp.newBuilder(modifiedAt_).mergeFrom(value).buildPartial();
        } else {
          modifiedAt_ = value;
        }
        onChanged();
      } else {
        modifiedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public Builder clearModifiedAt() {
      if (modifiedAtBuilder_ == null) {
        modifiedAt_ = null;
        onChanged();
      } else {
        modifiedAt_ = null;
        modifiedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public com.google.protobuf.Timestamp.Builder getModifiedAtBuilder() {
      
      onChanged();
      return getModifiedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedAtOrBuilder() {
      if (modifiedAtBuilder_ != null) {
        return modifiedAtBuilder_.getMessageOrBuilder();
      } else {
        return modifiedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : modifiedAt_;
      }
    }
    /**
     * <pre>
     * When the workflow version evaluation was modified.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp modified_at = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getModifiedAtFieldBuilder() {
      if (modifiedAtBuilder_ == null) {
        modifiedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getModifiedAt(),
                getParentForChildren(),
                isClean());
        modifiedAt_ = null;
      }
      return modifiedAtBuilder_;
    }

    private java.lang.Object targetNodeId_ = "";
    /**
     * <pre>
     * The ID of the node that is being evaluated.
     * </pre>
     *
     * <code>string target_node_id = 13;</code>
     * @return The targetNodeId.
     */
    public java.lang.String getTargetNodeId() {
      java.lang.Object ref = targetNodeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetNodeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the node that is being evaluated.
     * </pre>
     *
     * <code>string target_node_id = 13;</code>
     * @return The bytes for targetNodeId.
     */
    public com.google.protobuf.ByteString
        getTargetNodeIdBytes() {
      java.lang.Object ref = targetNodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the node that is being evaluated.
     * </pre>
     *
     * <code>string target_node_id = 13;</code>
     * @param value The targetNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetNodeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetNodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the node that is being evaluated.
     * </pre>
     *
     * <code>string target_node_id = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetNodeId() {
      
      targetNodeId_ = getDefaultInstance().getTargetNodeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the node that is being evaluated.
     * </pre>
     *
     * <code>string target_node_id = 13;</code>
     * @param value The bytes for targetNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetNodeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetNodeId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clarifai.api.WorkflowVersionEvaluation)
  }

  // @@protoc_insertion_point(class_scope:clarifai.api.WorkflowVersionEvaluation)
  private static final com.clarifai.grpc.api.WorkflowVersionEvaluation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.clarifai.grpc.api.WorkflowVersionEvaluation();
  }

  public static com.clarifai.grpc.api.WorkflowVersionEvaluation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkflowVersionEvaluation>
      PARSER = new com.google.protobuf.AbstractParser<WorkflowVersionEvaluation>() {
    @java.lang.Override
    public WorkflowVersionEvaluation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkflowVersionEvaluation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkflowVersionEvaluation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkflowVersionEvaluation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.clarifai.grpc.api.WorkflowVersionEvaluation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

