# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Prepare the API keys & run tests
      env:
        CLARIFAI_USER_EMAIL: ${{ secrets.CLARIFAI_USER_EMAIL }}
        CLARIFAI_USER_PASSWORD: ${{ secrets.CLARIFAI_USER_PASSWORD }}
      shell: bash
      run: |
        export CLARIFAI_APP_ID="$(python scripts/app_and_key_for_tests.py --create-app java-github)"
        export CLARIFAI_API_KEY="$(python scripts/app_and_key_for_tests.py --create-key ${CLARIFAI_APP_ID})"
        python scripts/app_and_key_for_tests.py --create-workflow ${CLARIFAI_API_KEY}
        ./gradlew test --tests *Grpc*Test
        ./gradlew test --tests *Json*Test
    - name: Slack Notify
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_ICON: "https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png"
        SLACK_USERNAME: "GitHub Alerts"
        SLACK_CHANNEL: "#grpc-client-repo-alerts"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Test failure"
        SLACK_FOOTER: "Clarifai Java GRPC Repo"
